Repository line/centraldogma, pull requests merged in 2018-06, with the labels that each got.

#239 Fix flaky tests in ArmeriaCentralDogmaBuilderTest
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
Labels: cleanup

#240 Fix a bug where ContentServiceV1.getFiles() does not apply JSON path query for watch responses
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
Labels: defect

#243 Fix a bug where jumping to a revision in file list view did not work
  server/src/main/resources/webapp/scripts/components/entities/repository.service.js
Labels: defect

#244 Change Go client library corrsponding to the changes in HTTP API
  client/go/dogma/content_service.go
  client/go/dogma/content_service_test.go
  client/go/dogma/dogma.go
  client/go/dogma/watch_service.go
  client/go/dogma/watch_service_test.go
Labels: breaking-change, improvement

#246 Provide error information in Go client
  client/go/dogma/dogma.go
Labels: defect

#247 Do not list partially-created projects unless necessary
  it/src/test/java/com/linecorp/centraldogma/it/RepositoryManagementTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/AbstractPermissionCheckingDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializingCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/StorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/Project.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtilTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/ThriftBackwardCompatibilityTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/plugin/PluginTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapperTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryMigrationTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerRule.java
Labels: defect

#248 Consistent HTTP API error response
  client/go/dogma/watch_service.go
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LogoutService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/util/RestfulJsonResponseConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/AbstractPermissionCheckingDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/AbstractRoleCheckingDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/AdministratorsOnly.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/CreateApiResponseConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiResponseConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
Labels: improvement

#249 Update Armeria to 0.66.0
  dependencies.yml
Labels: dependencies

#250 Use HttpApiExceptionHandler for v0 RepositoryService
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/resources/webapp/i18n/en.main.json
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.edit.controller.js
  server/src/main/resources/webapp/scripts/components/util/api.service.js
Labels: defect

#252 Add introductory slides to the front page
  site/src/sphinx/index.rst
Labels: documentation

#253 Update dependencies
  NOTICE.txt
  client/java-spring-boot1-autoconfigure/build.gradle
  dependencies.yml
  licenses/LICENSE.javassist.mpl11.html
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
Labels: dependencies
