Repository line/centraldogma, pull requests merged in 2018-04, with the labels that each got.

#176 Allow empty lambdas in check style
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/CommitAndChangesConverter.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationWithClientFactoryTest.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/AuthorConverter.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/ChangeConverter.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/CommitConverter.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/EntryConverter.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/MarkupConverter.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/QueryConverter.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/RevisionConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/plugin/PluginException.java
  settings/checkstyle/checkstyle.xml
Labels: cleanup

#179 Do not create the 'main' repository.
  it/src/test/java/com/linecorp/centraldogma/it/CacheTest.java
  it/src/test/java/com/linecorp/centraldogma/it/RepositoryManagementTest.java
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializingCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/Project.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtilTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/plugin/PluginTest.java
  site/src/sphinx/auth.rst
  site/src/sphinx/client-cli.rst
  site/src/sphinx/concepts.rst
Labels: cleanup

#180 Fix an error which is not able to restore removed repository
  server/src/main/resources/webapp/scripts/components/entities/repository.service.js
Labels: defect

#181 Allow specifying multiple protocols on a single port
  dist/src/conf/dogma.json
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  site/src/sphinx/setup-configuration.rst
Labels: new-feature

#182 Add 500ms delay when refreshing web UI after metadata modification
  server/src/main/resources/webapp/scripts/app/app.js
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.project.controller.js
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.repository.controller.js
  server/src/main/resources/webapp/scripts/app/settings/tokens/tokens.controller.js
Labels: defect

#183 Make web UI better
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.project.controller.js
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.project.html
  server/src/main/resources/webapp/scripts/app/entities/projects/projects.html
  server/src/main/resources/webapp/scripts/app/settings/tokens/tokens.html
  site/src/sphinx/_images/auth_1.png
  site/src/sphinx/_images/auth_2.png
  site/src/sphinx/_images/auth_3.png
  site/src/sphinx/_images/auth_4.png
  site/src/sphinx/auth.rst
Labels: documentation

#187 Upgrade Go version to 1.10.1
  client/go/build.gradle
  client/go/dogma/dogma.go
Labels: dependencies

#186 Try again quietly when LDAP server is unavailable
  server/src/main/java/com/linecorp/centraldogma/server/support/shiro/SearchFirstActiveDirectoryRealm.java
Labels: new-feature

#185 Add Caffeine cache for session information
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogmaBuilder.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/AccessToken.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/CentralDogmaSecurityManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LegacyToken.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/Repository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/RepositoryCache.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginAndLogoutTest.java
  site/src/sphinx/setup-configuration.rst
Labels: improvement

#189 Make searching available
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
Labels: defect

#193 Support Spring Boot 1 and 2
  client/java-spring-boot1-autoconfigure/build.gradle
  client/java-spring-boot1-starter/build.gradle
  settings.gradle
Labels: new-feature

#192 Fix RejectedExecutionException when mirroring workers are busy
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/Mirror.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServiceTest.java
Labels: defect

#190 Update dependencies
  dependencies.yml
Labels: dependencies

#194 Normalize the path parameter in HTTP API v1
  client/go/dogma/content_service.go
  client/go/dogma/content_service_test.go
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/EntryDto.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/resources/webapp/scripts/app/entities/repositories/repositories.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.edit.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.new.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.history.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.query.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.search.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.tree.controller.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.tree.html
  server/src/main/resources/webapp/scripts/components/entities/repository.service.js
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
Labels: defect

#196 Add a test case that ensures 'from/toRevision' is renamed to 'from/to'
  common-legacy/src/test/java/com/linecorp/centraldogma/internal/thrift/ThriftTextCompatibilityTest.java
Labels: improvement

#199 Allow accessing `metadata.json` to only administrators
  it/src/test/java/com/linecorp/centraldogma/it/RepositoryManagementTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LogoutService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/AbstractPermissionCheckingDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializingCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtilTest.java
Labels: defect

#200 Use command executor when creating a repository during migration
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtil.java
Labels: defect

#203 Do not allow removing meta repository
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.project.html
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
Labels: defect

#205 Update dependencies
  build.gradle
  client/java-spring-boot1-autoconfigure/build.gradle
  dependencies.yml
  dist/build.gradle
Labels: dependencies

#202 Add maxCommits url query to the REST API
  client/go/dogma/cmd/cli_cmds.go
  client/go/dogma/cmd/log_cmd.go
  client/go/dogma/content_service.go
  client/go/dogma/content_service_test.go
  client/go/dogma/dogma.go
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
Labels: new-feature

#204 Do not allow any operations when server is shutting down or a reposit…
  server/src/jmh/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryBenchmark.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/StorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitWatchers.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/Converter.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/plugin/PluginTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapperTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitIdDatabaseTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryMigrationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerRule.java
Labels: defect
