Repository line/centraldogma, pull requests merged in 2018-11, with the labels that each got.

#302 Remove Guice from the build dependencies / Update Go
  build.gradle
  cli/build.gradle
  dist/build.gradle
Labels: cleanup, dependencies

#301 Interrupt Central Dogma server startup process if stop is requested.
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/AbstractCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/NoneReplicationConfigTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/StartStopWithoutInitialQuorumTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  testing/src/main/java/com/linecorp/centraldogma/testing/CentralDogmaRule.java
Labels: defect, new-feature

#303 Update documentation for configuring replication
  site/src/sphinx/setup-configuration.rst
Labels: documentation

#304 Fix flaky ZooKeeperCommandExecutorTest.testLogWatch()
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
Labels: cleanup

#307 Add the path to Central Dogma bin directory to PATH environment variable
  dist/Dockerfile
Labels: defect

#309 Specify maxparallel in chmod
  cli/build.gradle
Labels: cleanup

#313 Copy dependencies for saml and shiro modules to lib directory
  dist/build.gradle
Labels: defect

#316 Fix a bug where serverId autodetection fails when more than one NIC h…
  server/src/main/java/com/linecorp/centraldogma/server/ZooKeeperReplicationConfig.java
Labels: defect

#317 Make JCommander an optional dependency
  server/build.gradle
Labels: dependencies

#318 Update CLI to use the latest Go client version
  cli/build.gradle
Labels: dependencies
