Repository line/centraldogma, pull requests merged in 2018-12, with the labels that each got.

#321 Add a document about mergeFiles
  site/src/sphinx/client-java.rst
Labels: documentation

#325 Adjust timeout for HTTP `watch` requests according to `wait` parameter
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/CentralDogmaClientTimeoutScheduler.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/CentralDogmaTimeoutSchedulerTest.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/WatchTimeout.java
  common/src/test/java/com/linecorp/centraldogma/internal/api/v1/WatchTimeoutTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaTimeoutScheduler.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1TestBase.java
Labels: defect

#327 Adjust timeout for WatchService
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/WatchTimeout.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
Labels: defect

#328 Redirect to the first requested URL after SAML SSO performed
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthSsoHandler.java
  server/src/main/resources/webapp/scripts/app/app.js
Labels: improvement

#329 Fix a notification message when a guest user tries to create a new re…
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/HasReadPermission.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/HasWritePermission.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ProjectMembersOnly.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ProjectOwnersOnly.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresAdministrator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresAdministratorDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresReadPermission.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRole.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRoleDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresWritePermission.java
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.delete.controller.js
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
Labels: defect

#335 Make client-side health check interval configurable / Increase the de…
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
Labels: defect, new-feature

#334 Fix IndexOutOfBoundsException when watching via HTTP API
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/WatchResultDto.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
Labels: defect

#339 Update dependencies
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-spring-boot1-autoconfigure/build.gradle
  dependencies.yml
  server/src/test/java/com/linecorp/centraldogma/server/ContentCompressionTest.java
Labels: dependencies

#340 Cache in find() when getFile() is called with the query whose type is…
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
Labels: improvement

#341 Update dependencies
  build.gradle
  dependencies.yml
Labels: dependencies
