Repository line/centraldogma, pull requests merged in 2018-08, with the labels that each got.

#265 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#266 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#269 Update dependencies
  build.gradle
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
Labels: dependencies

#271 Change base image to 'openjdk:8'
  dist/Dockerfile
Labels: defect

#272 Fix frontend-side route conflicts
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.project.html
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.repository.html
  server/src/main/resources/webapp/scripts/app/entities/projects/project.html
  server/src/main/resources/webapp/scripts/app/entities/projects/projects.html
  server/src/main/resources/webapp/scripts/app/entities/projects/projects.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repositories.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.controller.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.edit.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.file.new.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.history.controller.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.history.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.new.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.query.controller.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.query.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.search.controller.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.search.html
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.tree.controller.js
  server/src/main/resources/webapp/scripts/app/entities/repositories/repository.tree.html
Labels: breaking-change, defect

#275 Update Armeria to 0.70.1
  dependencies.yml
Labels: dependencies

#276 Change call to change listener to invoke on updated value
  client/java/src/main/java/com/linecorp/centraldogma/client/updater/CentralDogmaBeanFactory.java
  it/src/test/java/com/linecorp/centraldogma/it/updater/CentralDogmaBeanTest.java
Labels: defect
