Repository line/centraldogma, pull requests merged in 2018-07, with the labels that each got.

#254 Upgrade gradle to 4.8.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#256 Use Java 10 by default.
  .appveyor.yml
  .gitignore
  .travis.yml
  .travis/install-jdk.sh
  build.gradle
Labels: cleanup

#257 Add 'ID' field to credentials
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/AbstractMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/MirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/NoneMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/PasswordMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/PublicKeyMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/credential/MirrorCredentialTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/credential/NoneMirrorCredentialTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/credential/PasswordMirrorCredentialTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/credential/PublicKeyMirrorCredentialTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepositoryTest.java
  site/src/sphinx/mirroring.rst
Labels: new-feature

#261 Do not use framed version of Javadoc
  site/src/sphinx/_extensions/api.py
  site/src/sphinx/client-java.rst
  site/src/sphinx/setup-configuration.rst
Labels: documentation

#262 Use OpenJDK 10 instead of Oracle JDK 10 for build stability
  .travis.yml
Labels: cleanup

#263 Update dependencies
  build.gradle
  dependencies.yml
Labels: dependencies
