Repository line/centraldogma, pull requests merged in 2018-05, with the labels that each got.

#208 Backport the site improvements from Armeria
  site/build.gradle
  site/src/sphinx/_extensions/api.py
  site/src/sphinx/_extensions/parsed_literal_highlight.py
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/auth.rst
  site/src/sphinx/client-java.rst
  site/src/sphinx/conf.py
Labels: documentation

#209 Use Highlight.js instead of Pygments for syntax highlighting
  site/src/sphinx/_extensions/highlightjs.py
  site/src/sphinx/_extensions/parsed_literal_highlight.py
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/_templates/layout.html
  site/src/sphinx/concepts.rst
  site/src/sphinx/conf.py
Labels: documentation

#211 Compress API responses if requested
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/test/java/com/linecorp/centraldogma/server/ContentCompressionTest.java
Labels: new-feature

#213 Use repository executor when processing watch request
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
Labels: defect

#105 Add CentralDogma backed EndpointGroup
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroup.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/EndpointListCodecUtils.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/EndpointListDecoder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/JsonEndpointListDecoder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/TextEndpointListDecoder.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/JsonEndpointListDecoderTest.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/TextEndpointListDecoderTest.java
  it/src/test/java/com/linecorp/centraldogma/it/CentralDogmaEndpointGroupTest.java
Labels: new-feature

#216 Fix watcher leaks
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
Labels: defect

#219 Fix a bug where calling API with wrong HTTP method to check security …
  client/go/dogma/dogma.go
Labels: defect

#220 Update IntelliJ IDEA code style and inspection profile
  settings/intellij_idea/settings.jar
Labels: miscellaneous

#218 Update metadata when creating/removing a project/repository by Thrift…
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/Project.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/ThriftBackwardCompatibilityTest.java
Labels: defect

#221 Fix a bug where checking whether the repository is migrated or not
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtil.java
Labels: defect

#217 Add jitters to mirroring jobs
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/Mirror.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirrorTest.java
Labels: improvement

#222 Apply jitter to watch timeout
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
Labels: improvement

#223 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#225 Update Armeria to 0.64.0
  dependencies.yml
Labels: dependencies

#228 Automatic client-side load balancing using DNS lookup
  client/go/dogma/watch_service.go
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CompositeEndpointGroup.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
  client/java-armeria/src/test/resources/centraldogma-profile-test-xip.properties
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/HttpApiV1Constants.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  site/src/sphinx/client-java.rst
  testing/src/main/java/com/linecorp/centraldogma/testing/CentralDogmaRule.java
Labels: new-feature

#224 Refactor the enums stringer
  client/go/dogma/content_service.go
  client/go/dogma/enums.go
Labels: improvement

#229 Rename centraldogma-client-java-spring-boot1-* to centraldogma-client-spring-boot1-*
  build.gradle
Labels: breaking-change, defect

#230 Add RepositoryMetadata of `meta` repository when initializing metadata
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/ProjectInitializingCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/ThriftBackwardCompatibilityTest.java
Labels: defect

#234 Update Gradle plugins
  build.gradle
  dependencies.yml
Labels: dependencies

#233 Allow using different ports for cleartext and TLS when using a client profile
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
  client/java-armeria/src/test/resources/centraldogma-profile-test-xip.properties
  client/java-armeria/src/test/resources/centraldogma-profiles-test.json
  client/java-spring-boot-autoconfigure/src/test/resources/centraldogma-profile-confTest.properties
  client/java-spring-boot-autoconfigure/src/test/resources/centraldogma-profiles-test.json
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogmaBuilder.java
  client/java/src/main/java/com/linecorp/centraldogma/client/ClientProfile.java
  client/java/src/test/java/com/linecorp/centraldogma/client/CentralDogmaBuilderTest.java
  client/java/src/test/resources/centraldogma-profile-bar.properties
  client/java/src/test/resources/centraldogma-profile-foo.properties
  client/java/src/test/resources/centraldogma-profile-qux.properties
  client/java/src/test/resources/centraldogma-profiles-test.json
  client/java/src/test/resources/centraldogma-profiles.json
  site/src/sphinx/_static/schema-centraldogma-profiles.json
  site/src/sphinx/client-java.rst
Labels: breaking-change, new-feature

#235 Update Armeria from 0.64.0 to 0.65.1
  dependencies.yml
  it/src/test/java/com/linecorp/centraldogma/it/CentralDogmaEndpointGroupTest.java
Labels: dependencies
