Repository line/centraldogma, pull requests merged in 2018-03, with the labels that each got.

#142 Implement read-only mode
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatch.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
Labels: new-feature

#144 Choose the last matching client profile
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogmaBuilder.java
  client/java/src/test/java/com/linecorp/centraldogma/client/CentralDogmaBuilderTest.java
  client/java/src/test/resources/centraldogma-profile-qux.properties
Labels: defect

#145 Expose web session timeout configuration
  dist/src/conf/dogma.json
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/CentralDogmaSecurityManager.java
  site/src/sphinx/setup-configuration.rst
Labels: new-feature

#149 Update Armeria to 0.59.0
  common/src/main/java/com/linecorp/centraldogma/internal/Jackson.java
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LogoutService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/Token.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/model/UserAndTimestamp.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/TokenService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
Labels: dependencies

#160 Fix TTEXT backward compatibility issue with `from` and `to` parameters
  common/build.gradle
Labels: defect

#164 Allow read-only mode API only to administrators
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/UserWithToken.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/RepositoryUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/metadata/Token.java
  server/src/main/resources/webapp/i18n/en.main.json
  server/src/main/resources/webapp/scripts/app/settings/tokens/token.generated.html
  server/src/main/resources/webapp/scripts/app/settings/tokens/token.new.controller.js
  server/src/main/resources/webapp/scripts/app/settings/tokens/token.new.html
  server/src/main/resources/webapp/scripts/app/settings/tokens/tokens.html
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/MigrationUtilTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerRule.java
  testing/src/main/java/com/linecorp/centraldogma/testing/CentralDogmaRule.java
Labels: new-feature

#147 Expose TLS configuration
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogmaBuilder.java
  dist/src/conf/dogma.json
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/TlsConfig.java
  server/src/test/java/com/linecorp/centraldogma/server/ConfigDeserializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/TlsServerTest.java
  site/src/sphinx/setup-configuration.rst
  testing/src/main/java/com/linecorp/centraldogma/testing/CentralDogmaRule.java
Labels: new-feature

#165 Fix a condition to do not create duplicated armeriaClient
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationWithClientFactoryTest.java
Labels: defect

#168 Add vectorized logo
  .gitattributes
  site/src/sphinx/_static/central_dogma.ai
  site/src/sphinx/_static/central_dogma.svg
Labels: documentation

#141 Provide Go client library
  client/go/build.gradle
  client/go/dogma/content_service.go
  client/go/dogma/content_service_test.go
  client/go/dogma/dogma.go
  client/go/dogma/dogma_test.go
  client/go/dogma/enums.go
  client/go/dogma/project_service.go
  client/go/dogma/project_service_test.go
  client/go/dogma/repository_service.go
  client/go/dogma/repository_service_test.go
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/AccessToken.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/CommitDto.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/EntryDto.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/WatchResultDto.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/main/resources/webapp/scripts/components/auth/provider/auth.session.service.js
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginAndLogoutTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/authentication/ReplicatedLoginAndLogoutTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
Labels: new-feature

#170 Add /api/v1/login and /api/v1/logout
  client/go/dogma/dogma.go
  client/go/dogma/dogma_test.go
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginAndLogoutTest.java
Labels: new-feature

#167 Add a property whether case-sensitive matching is performed when logi…
  dist/src/conf/dogma.json
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/authentication/LoginService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  site/src/sphinx/setup-configuration.rst
Labels: new-feature

#171 Do not exclude net.minidev:json-smart from dependencies
  common/src/main/java/com/linecorp/centraldogma/internal/Jackson.java
  dependencies.yml
Labels: defect
