Repository line/centraldogma, pull requests merged in 2019-09, with the labels that each got.

#436 Switch from GitHub ribbons to corners
  site/src/sphinx/_static/center_page.js
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/_templates/layout.html
Labels: documentation

#439 Update Go client library to 4c736b80420b1476e8003a2236f8ff680f17…
  cli/build.gradle
Labels: dependencies

#438 Update frontend dependencies
  server-auth/webapp/yarn.lock
Labels: dependencies

#437 Retry client requests on replication lag
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogmaBuilder.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  client/java/src/test/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogmaTest.java
Labels: improvement

#441 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  server/src/test/java/com/linecorp/centraldogma/server/auth/ReplicatedLoginAndLogoutTest.java
  settings/checkstyle/checkstyle.xml
Labels: dependencies

#442 Respond '204 No Content' when attempting to get no content.
  common/src/main/java/com/linecorp/centraldogma/common/Entry.java
  common/src/main/java/com/linecorp/centraldogma/common/EntryNoContentException.java
  common/src/test/java/com/linecorp/centraldogma/common/EntryTest.java
  it/src/test/java/com/linecorp/centraldogma/it/FileManagementTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
Labels: defect

#444 Do not run `GitAuthTest` by default
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorAuthTest.java
Labels: cleanup

#445 Update dependencies
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
Labels: dependencies

#434 Implement client-side JSON filtering
  client/java/src/main/java/com/linecorp/centraldogma/client/TransformingWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/client/Watcher.java
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
Labels: new-feature

#451 Add Spring Boot settings for replication lag tolerance
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaSettings.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationOtherPropsTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationProfileTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationSpringProfileTest.java
  client/java-spring-boot-autoconfigure/src/test/resources/config/application-otherProps.yml
Labels: new-feature

#452 Simplified checking of empty content http-status.
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
Labels: cleanup

#454 Move down the GitHub corner on mobile view
  site/src/sphinx/_static/overrides.css
Labels: documentation

#450 Add logging to `ReplicationLagTolerantCentralDogma`
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  client/java/src/test/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogmaTest.java
Labels: improvement

#455 Update Armeria from 0.92.0 to 0.93.0
  dependencies.yml
Labels: dependencies
