Repository line/centraldogma, pull requests merged in 2019-07, with the labels that each got.

#413 Update dependencies
  .appveyor.yml
  .travis.yml
  build.gradle
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings/checkstyle/checkstyle-suppressions.xml
  settings/checkstyle/checkstyle.xml
Labels: dependencies

#417 Do not fail `GitMirrorAuthTest` when failed to load an SSH key
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorAuthTest.java
Labels: cleanup

#418 Fix API links in the web site
  site/src/sphinx/_extensions/api.py
Labels: documentation

#419 Update frontend dependencies
  server-auth/webapp/yarn.lock
Labels: dependencies

#420 Fix the shell script warnings issued by shellcheck
  dist/src/bin/common.sh
  dist/src/bin/dogma
  dist/src/bin/shutdown
  dist/src/bin/startup
Labels: cleanup

#416 Automatic purging of removed repositories and projects
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTest.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  common-legacy/src/main/thrift/CentralDogma.thrift
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/HttpApiV1Constants.java
  dist/src/conf/dogma.json
  it/src/test/java/com/linecorp/centraldogma/it/ProjectManagementTest.java
  it/src/test/java/com/linecorp/centraldogma/it/RepositoryManagementTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/PluginGroup.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandType.java
  server/src/main/java/com/linecorp/centraldogma/server/command/PurgeProjectCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/PurgeRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginContext.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/StorageManager.java
  server/src/main/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
  server/src/test/java/com/linecorp/centraldogma/server/CentralDogmaConfigTest.java
  server/src/test/java/com/linecorp/centraldogma/server/PluginGroupTest.java
  server/src/test/java/com/linecorp/centraldogma/server/command/PurgeProjectCommandTest.java
  server/src/test/java/com/linecorp/centraldogma/server/command/PurgeRepositoryCommandTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/DefaultProjectManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapperTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryMigrationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  site/src/sphinx/setup-configuration.rst
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerRule.java
Labels: new-feature

#422 Fix XSS on a search feature
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/resources/webapp/scripts/components/util/notification-util.service.js
  server/src/main/resources/webapp/scripts/components/util/string-util.service.js
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
  site/src/sphinx/known-issues.rst
Labels: defect

#423 Update dependencies
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutSchedulerTest.java
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  server-auth/webapp/build.gradle
  server-auth/webapp/yarn.lock
Labels: dependencies

#424 Update sphinx-gradle-plugin from 2.5.0 to 2.6.0
  dependencies.yml
  site/src/sphinx/conf.py
Labels: dependencies
