Repository line/centraldogma, pull requests merged in 2019-05, with the labels that each got.

#397 Improve the overall look and feel of the web site
  dependencies.yml
  site/src/sphinx/_static/add_badges.js
  site/src/sphinx/_static/center_page.js
  site/src/sphinx/_static/overrides.css
  site/src/sphinx/_templates/layout.html
  site/src/sphinx/conf.py
  site/src/sphinx/index.rst
Labels: cleanup, documentation

#399 Change the Java download links to refer to https://adoptopenjdk.net/
  site/src/sphinx/index.rst
  site/src/sphinx/setup-installation.rst
Labels: documentation

#398 Update CLI tag
  cli/build.gradle
Labels: defect

#401 Update dependencies
  client/java-spring-boot1-autoconfigure/build.gradle
  dependencies.yml
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthSsoHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/RequestAlreadyTimedOutException.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/FailFastUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
Labels: defect, dependencies

#402 Add missing `evaluationDependsOn` to dist/build.gradle
  .post-release-msg
  cli/build.gradle
  dist/build.gradle
Labels: cleanup
