Repository line/centraldogma, pull requests merged in 2019-11, with the labels that each got.

#458 Add more debug logging to `ReplicationLagTolerantCentralDogma`
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
Labels: cleanup

#459 Update dependencies
  build.gradle
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#461 Update Slack shared invites and use `rel=nofollow` / Update `CON…
  CONTRIBUTING.md
  README.md
  site/src/sphinx/_static/add_badges.js
  site/src/sphinx/known-issues.rst
Labels: miscellaneous

#462 Update dependencies
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutScheduler.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutSchedulerTest.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationWithClientFactoryTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchTest.java
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthProvider.java
  server-auth/shiro/src/main/java/com/linecorp/centraldogma/server/auth/shiro/ShiroAuthProvider.java
  server-auth/shiro/src/test/java/com/linecorp/centraldogma/server/auth/shiro/ShiroLoginAndLogoutTest.java
  server-auth/webapp/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthProvider.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresAdministratorDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRoleDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaExceptionTranslator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaTimeoutScheduler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/TokenlessClientLogger.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataServiceInjector.java
  server/src/test/java/com/linecorp/centraldogma/server/ContentCompressionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/auth/ReplicatedLoginAndLogoutTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1TestBase.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/MergeFileTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/thrift/TokenlessClientLoggerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/ThriftBackwardCompatibilityTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthMessageUtil.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthProvider.java
  testing/src/main/java/com/linecorp/centraldogma/testing/CentralDogmaRule.java
Labels: dependencies

#463 Unwrap CompletionException to check actual thrown exception
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  client/java/src/test/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogmaTest.java
Labels: defect
