Repository line/centraldogma, pull requests merged in 2019-03, with the labels that each got.

#349 Show configured title on the web-based administrative console
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/resources/webapp/scripts/components/navbar/navbar.controller.js
  server/src/main/resources/webapp/scripts/components/navbar/navbar.html
  site/src/sphinx/setup-configuration.rst
Labels: new-feature

#348 Remove commons-daemon from dependencies
  .gitattributes
  NOTICE.txt
  dependencies.yml
  dist/Dockerfile
  dist/src/bin/common.sh
  dist/src/bin/jsvc.linux-x86_64
  dist/src/bin/jsvc.osx
  dist/src/bin/shutdown
  dist/src/bin/startup
  licenses/LICENSE.commons-daemon.al20.txt
  licenses/LICENSE.jnr-posix.epl20.txt
  server/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/Main.java
Labels: dependencies, improvement

#351 Use react-scripts instead of react-scripts-ts for webapp in server-auth
  server-auth/webapp/images.d.ts
  server-auth/webapp/package.json
  server-auth/webapp/tsconfig.json
  server-auth/webapp/tsconfig.prod.json
  server-auth/webapp/tsconfig.test.json
  server-auth/webapp/yarn.lock
Labels: cleanup, dependencies

#352 Make webAppTitle fully customizable
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/Main.java
  server/src/main/resources/webapp/i18n/en.main.json
  server/src/main/resources/webapp/index.html
  server/src/main/resources/webapp/scripts/components/navbar/navbar.controller.js
  server/src/main/resources/webapp/scripts/components/navbar/navbar.html
  server/src/main/resources/webapp/scripts/components/title/title.service.js
  site/src/sphinx/setup-configuration.rst
Labels: defect, improvement

#350 HTTP-based Java client
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutScheduler.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTest.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutSchedulerTest.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaTest.java
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/RepositoryInfo.java
  common/src/main/java/com/linecorp/centraldogma/common/AuthorizationException.java
  common/src/main/java/com/linecorp/centraldogma/common/Entry.java
  common/src/main/java/com/linecorp/centraldogma/internal/Util.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/EntryDto.java
  it/src/test/java/com/linecorp/centraldogma/it/AbstractMultiClientTest.java
  it/src/test/java/com/linecorp/centraldogma/it/CacheTest.java
  it/src/test/java/com/linecorp/centraldogma/it/ClientType.java
  it/src/test/java/com/linecorp/centraldogma/it/FileHistoryAndDiffTest.java
  it/src/test/java/com/linecorp/centraldogma/it/FileManagementTest.java
  it/src/test/java/com/linecorp/centraldogma/it/GetDiffTest.java
  it/src/test/java/com/linecorp/centraldogma/it/GetFileTest.java
  it/src/test/java/com/linecorp/centraldogma/it/GracefulShutdownTest.java
  it/src/test/java/com/linecorp/centraldogma/it/MergeFileTest.java
  it/src/test/java/com/linecorp/centraldogma/it/PreviewDiffsTest.java
  it/src/test/java/com/linecorp/centraldogma/it/ProjectManagementTest.java
  it/src/test/java/com/linecorp/centraldogma/it/RepositoryManagementTest.java
  it/src/test/java/com/linecorp/centraldogma/it/RevisionNormalizationTest.java
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
  server-auth/webapp/src/react-app-env.d.ts
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/ChangesRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/PathPatternFilter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/test/java/com/linecorp/centraldogma/server/ContentCompressionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1TestBase.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/ThriftBackwardCompatibilityTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/thrift/TokenlessClientLoggerTest.java
  site/src/sphinx/client-java.rst
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthMessageUtil.java
  testing/src/main/java/com/linecorp/centraldogma/testing/CentralDogmaRule.java
Labels: new-feature

#355 Update dependencies
  build.gradle
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
Labels: dependencies

#357 Remove the outdated section about Java client in documentation
  site/src/sphinx/auth.rst
Labels: documentation

#359 Add more languages to Highlight.js / Overall highliting cleanup
  site/src/sphinx/_templates/layout.html
  site/src/sphinx/auth.rst
  site/src/sphinx/client-cli.rst
  site/src/sphinx/client-java.rst
  site/src/sphinx/index.rst
  site/src/sphinx/mirroring.rst
  site/src/sphinx/setup-configuration.rst
  site/src/sphinx/setup-installation.rst
Labels: documentation

#361 Fix a bug where access token in `application.yml` is not set to `Arme…
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationOtherPropsTest.java
  client/java-spring-boot-autoconfigure/src/test/resources/config/application-otherProps.yml
Labels: defect

#362 Allow sending an access token with `LegacyCentralDogmaBuilder`
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogmaBuilder.java
Labels: new-feature

#364 Do not perform unnecessary revision normalization.
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
Labels: defect

#365 Update dependencies
  NOTICE.txt
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  dependencies.yml
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  licenses/LICENSE.jnr-posix.epl20.txt
  server-auth/webapp/build.gradle
  server/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/Main.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java
Labels: dependencies

#367 Send a JSON response for authentication failures
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaAuthFailureHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/test/java/com/linecorp/centraldogma/server/CentralDogmaAuthFailureHandlerTest.java
Labels: defect

#370 Downgrade jGit from 5.3.0 to 5.2.1
  dependencies.yml
Labels: dependencies

#369 Update the `last_revision` on every commit
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: defect

#371 Do not compare Git trees when lastKnownRevision is 1.
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
Labels: performance

#372 Do not traverse the whole tree when comparing two trees.
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DiffEntry.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DiffScanner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
Labels: performance

#373 Do not execute repository job when the request has already timed out
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
Labels: performance

#374 Cache the diff result in `DiffScanner`
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DiffScanner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
Labels: performance
