Repository line/centraldogma, pull requests merged in 2019-06, with the labels that each got.

#404 Add properties to CentralDogmaConfig for configuring trusted proxy addresses
  dist/src/conf/dogma.json
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/test/java/com/linecorp/centraldogma/server/CentralDogmaConfigTest.java
  site/src/sphinx/setup-configuration.rst
Labels: new-feature

#405 Update dependencies
  dependencies.yml
  server-auth/webapp/build.gradle
  server-auth/webapp/package.json
  server-auth/webapp/src/App.tsx
  server-auth/webapp/yarn.lock
Labels: dependencies

#406 Send `400 Bad Request` when receiving an invalid SAML request
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  dependencies.yml
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthProvider.java
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthSsoHandler.java
  server-auth/saml/src/test/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthTest.java
  server-auth/shiro/src/main/java/com/linecorp/centraldogma/server/auth/shiro/LoginService.java
  server-auth/shiro/src/test/java/com/linecorp/centraldogma/server/auth/shiro/ShiroLoginAndLogoutTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthProvider.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/ChangesRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/CommitMessageRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/MergeQueryRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/QueryRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
  server/src/test/java/com/linecorp/centraldogma/server/CentralDogmaAuthFailureHandlerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/ContentCompressionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/MetricsTest.java
  server/src/test/java/com/linecorp/centraldogma/server/auth/ReplicatedLoginAndLogoutTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/MergeFileTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/MergeQueryRequestConverterTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/QueryRequestConverterTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/ThriftBackwardCompatibilityTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthMessageUtil.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthProvider.java
Labels: defect, dependencies

#408 Update requestTimeout when using Thrift watch API
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
Labels: defect

#409 Move metadata package to the public API
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/AuthUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/CsrfTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/LegacyToken.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/SessionTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/UserService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresAdministratorDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresReadPermission.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRole.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRoleDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresWritePermission.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/HolderWithRevision.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Identifiable.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Member.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataServiceInjector.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MigrationUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Permission.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/ProjectMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/ProjectRole.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositorySupport.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Token.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/TokenRegistration.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Tokens.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/User.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/UserAndTimestamp.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/UserWithToken.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/package-info.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MigrationUtilTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/ThriftBackwardCompatibilityTest.java
Labels: cleanup

#410 Add the default metadata when a repository has missing metadata
  common-legacy/build.gradle
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MissingRepositoryMetadataTest.java
Labels: defect

#412 Use `jakarta.annotation-api` instead of `javax.annotation-api`
  NOTICE.txt
  common-legacy/build.gradle
  dependencies.yml
Labels: dependencies
