Repository line/centraldogma, pull requests merged in 2019-04, with the labels that each got.

#375 Cache the comparison result between two Git trees / Fail the timed-ou…
  common/src/main/java/com/linecorp/centraldogma/common/Revision.java
  dependencies.yml
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
  server/src/jmh/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryBenchmark.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/CacheableCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryCache.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableFindCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableFindLatestRevCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableHistoryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableMergeQueryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableMultiDiffCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableQueryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableSingleDiffCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CacheableCompareTreesCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitWatchers.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DiffEntry.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DiffScanner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/FailFastUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/PathPatternFilter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/ReadLockStamp.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapperTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitIdDatabaseTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryMigrationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/ReadLockStampTest.java
Labels: cleanup, dependencies, performance

#376 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/command/AbstractCommandExecutor.java
Labels: dependencies

#377 Add `fsync.warningthresholdms` property to `ZooKeeperCommandExecutor`
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: new-feature

#378 Add `revision` property to `EntryDto`
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/EntryDto.java
  server-auth/saml/src/test/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthTest.java
  server-auth/shiro/src/main/java/com/linecorp/centraldogma/server/auth/shiro/LoginService.java
  server-auth/shiro/src/test/java/com/linecorp/centraldogma/server/auth/shiro/ShiroLoginAndLogoutTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
  server/src/test/java/com/linecorp/centraldogma/server/auth/ReplicatedLoginAndLogoutTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ListCommitsAndDiffTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/MergeFileTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/metadata/ThriftBackwardCompatibilityTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthProvider.java
Labels: new-feature

#382 Fix a bug where `GitRepository.compareTrees()` operation is not cached.
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryCache.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManagerTest.java
Labels: defect

#386 Wait until process is terminated in stop script / Add visual feedback while waiting
  dist/src/bin/common.sh
  dist/src/bin/shutdown
  dist/src/bin/startup
Labels: defect

#387 Fix a watcher leak
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitWatchers.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
Labels: defect

#388 Fix a dead lock by reverting back to `ReentrantReadWriteLock`
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/CacheableCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryCache.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CacheableCompareTreesCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/ReadLockStamp.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/ReadLockStampTest.java
Labels: defect

#389 Add metrics
  build.gradle
  common/build.gradle
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/HttpApiV1Constants.java
  dependencies.yml
  it/src/test/java/com/linecorp/centraldogma/it/CacheTest.java
  server/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/PluginGroup.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/EmbeddedZooKeeper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryCache.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginContext.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/ProjectManager.java
  server/src/test/java/com/linecorp/centraldogma/server/MetricsTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerRule.java
Labels: breaking-change, new-feature

#390 Change meter ID prefix from 'dogma' to 'api'
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
Labels: cleanup

#391 Make client-side watch operations better-documented and less error-prone.
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/Latest.java
  client/java/src/main/java/com/linecorp/centraldogma/client/WatchConstants.java
  client/java/src/main/java/com/linecorp/centraldogma/client/Watcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/AbstractWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/FileWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/RepositoryWatcher.java
  site/src/sphinx/client-java.rst
Labels: documentation, new-feature

#383 Enlarge watcher timeout to give a user more chance to retry
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroup.java
  it/src/test/java/com/linecorp/centraldogma/it/CentralDogmaEndpointGroupTest.java
Labels: defect

#393 Remove '*.js' used for the old plugin support
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/es6-promise-3.0.2.js
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/polyfill-console.js
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/polyfill-timeout.js
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/require-2.1.22.js
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/require-overrides.js
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/startup.js
  server/src/main/resources/com/linecorp/centraldogma/server/internal/plugin/unsafe.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testHelloWorld/meta/hello_world.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testHelloWorld/meta/plugins.json
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testLoadFailure/meta/fail.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testLoadFailure/meta/plugins.json
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testPromise/meta/async_hello_world.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testPromise/meta/plugins.json
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testRequireJs/meta/baz.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testRequireJs/meta/foo.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testRequireJs/meta/plugins.json
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testRequireJs/meta/qux/bar.js
  server/src/test/resources/com/linecorp/centraldogma/server/internal/plugin/testRequireJs/meta/util/util.js
Labels: cleanup

#394 Make `ArmeriaCentralDogma` handle `2xx` responses better.
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  it/src/test/java/com/linecorp/centraldogma/it/FileManagementTest.java
Labels: defect

#395 Update dependencies
  client/java-spring-boot1-autoconfigure/build.gradle
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#396 Apply `ArmeriaClientConfigurator` after the internal decorators
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
Labels: defect
