Repository line/centraldogma, pull requests merged in 2020-04, with the labels that each got.

#507 Do not halt even if failed to schedule a purge task
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
Labels: defect

#509 More efficient history operation
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
Labels: improvement

#510 Do not halt even if failed to delete ZooKeeper logs
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: defect

#511 Fix a bug where a JSON file cannot be watched and fetched as String
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/FileWatcher.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/QueryConverter.java
  common-legacy/src/main/thrift/CentralDogma.thrift
  common/src/main/java/com/linecorp/centraldogma/common/Entry.java
  common/src/main/java/com/linecorp/centraldogma/common/IdentityQuery.java
  common/src/main/java/com/linecorp/centraldogma/common/JsonPathQuery.java
  common/src/main/java/com/linecorp/centraldogma/common/Query.java
  common/src/main/java/com/linecorp/centraldogma/common/QueryType.java
  common/src/test/java/com/linecorp/centraldogma/common/QueryTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/thrift/QueryConverterTest.java
  it/src/test/java/com/linecorp/centraldogma/it/GetFileTest.java
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/dto/NamedQueryDto.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/dto/QueryDto.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/RepositoryUtil.java
Labels: defect

#512 Update dependencies / Fix checkstyle violations
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTest.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroup.java
  client/java/src/main/java/com/linecorp/centraldogma/client/TransformingWatcher.java
  common/src/main/java/com/linecorp/centraldogma/common/RevisionJsonDeserializer.java
  common/src/main/java/com/linecorp/centraldogma/common/RevisionJsonSerializer.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchUtil.java
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthException.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/RawSessionJsonDeserializer.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/RawSessionJsonSerializer.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CreateProjectCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CreateRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CreateSessionCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/PurgeProjectCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/PurgeRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/PushCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/RemoveProjectCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/RemoveRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/RemoveSessionCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/RepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/UnremoveProjectCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/UnremoveRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorSchemes.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/StorageException.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  settings/checkstyle/checkstyle-suppressions.xml
  settings/checkstyle/checkstyle.xml
Labels: dependencies
