Repository line/centraldogma, pull requests merged in 2020-02, with the labels that each got.

#481 Update dependencies
  build.gradle
  dependencies.yml
Labels: dependencies

#478 Migrate unit tests to JUnit 5 (Part 3)
  build.gradle
  client/java-spring-boot-autoconfigure/build.gradle
  client/java-spring-boot1-autoconfigure/build.gradle
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorAuthTest.java
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/auth/ReplicatedLoginAndLogoutTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1TestBase.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/MergeFileTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
Labels: cleanup

#479 Upgrade Armeria version to 0.98.0
  build.gradle
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutScheduler.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTimeoutSchedulerTest.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroup.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CompositeEndpointGroup.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/WatchTimeout.java
  common/src/test/java/com/linecorp/centraldogma/internal/api/v1/WatchTimeoutTest.java
  dependencies.yml
  it/src/test/java/com/linecorp/centraldogma/it/CentralDogmaEndpointGroupTest.java
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthProviderFactory.java
  server-auth/shiro/src/main/java/com/linecorp/centraldogma/server/auth/shiro/LoginService.java
  server-auth/shiro/src/main/java/com/linecorp/centraldogma/server/auth/shiro/LogoutService.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/AuthUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/CsrfTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/OrElseDefaultHttpFileService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/SessionTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/DefaultLogoutService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/WatchService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/ChangesRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/CommitMessageRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaTimeoutScheduler.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataServiceInjector.java
  server/src/test/java/com/linecorp/centraldogma/server/ContentCompressionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/ThriftBackwardCompatibilityTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthProvider.java
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
Labels: dependencies

#482 Update frontend dependencies
  server-auth/webapp/build.gradle
  server-auth/webapp/yarn.lock
Labels: dependencies

#483 Use modern Gradle dependency API
  build.gradle
  client/java-armeria-legacy/build.gradle
  client/java-armeria/build.gradle
  client/java-spring-boot-autoconfigure/build.gradle
  client/java-spring-boot-starter/build.gradle
  client/java-spring-boot1-autoconfigure/build.gradle
  client/java-spring-boot1-starter/build.gradle
  client/java/build.gradle
  common-legacy/build.gradle
  common/build.gradle
  dist/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  it/build.gradle
  server-auth/saml/build.gradle
  server-auth/shiro/build.gradle
  server/build.gradle
  testing-internal/build.gradle
  testing/common/build.gradle
  testing/junit/build.gradle
  testing/junit4/build.gradle
Labels: cleanup

#484 Use Java 13 for building and releasing
  .appveyor.yml
  .travis.yml
  CONTRIBUTING.md
  build.gradle
Labels: dependencies

#485 Update Armeria from 0.98.0 to 0.98.1
  dependencies.yml
Labels: dependencies

#487 Downgrade Node.js to 10.19.0
  server-auth/webapp/build.gradle
Labels: dependencies

#488 Remove `:client:java-armeria-legacy` from Spring Boot integration
  client/java-spring-boot-autoconfigure/build.gradle
  client/java-spring-boot1-autoconfigure/build.gradle
  server-auth/webapp/yarn.lock
Labels: defect, dependencies

#489 Migrate more tests cases to JUnit 5
  client/java-spring-boot-autoconfigure/build.gradle
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationHostsTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationOtherPropsTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationProfileTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationSpringProfileTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationWithClientFactoryTest.java
  client/java-spring-boot1-autoconfigure/build.gradle
Labels: cleanup

#490 Fix version constraints in Spring Boot 1 modules
  .appveyor.yml
  build.gradle
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationHostsTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationOtherPropsTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationProfileTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationSpringProfileTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationWithClientFactoryTest.java
  client/java-spring-boot1-autoconfigure/build.gradle
  client/java-spring-boot1-starter/build.gradle
Labels: defect, dependencies

#491 Do not fail `watch` when `ClientFactory` is closed
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  it/src/test/java/com/linecorp/centraldogma/it/PrematureClientFactoryCloseTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
Labels: defect

#492 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: dependencies

#493 Fix Micrometer meter names
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/EmbeddedZooKeeper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
Labels: defect

#495 Do not log warnings about closed connections and streams
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
Labels: cleanup

#497 Fix the method name for bean creation of CentralDogma client
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
Labels: breaking change, cleanup

#498 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
Labels: dependencies

#499 Install java.util.logging-to-SLF4J bridge on startup
  server/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/Main.java
Labels: defect

#500 Clean up overall logging configuration
  dist/src/conf/logback.xml
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
Labels: improvement
