Repository line/centraldogma, pull requests merged in 2021-02, with the labels that each got.

#552 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#553 Add CentralDogmaEndpointGroupBuilder
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroup.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/CentralDogmaEndpointGroupBuilder.java
  it/src/test/java/com/linecorp/centraldogma/it/CentralDogmaEndpointGroupTest.java
Labels: new feature

#557 Leave client address on invalid access
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
Labels: improvement

#554 Fix that `mergeFiles` API modifies the content of the merge sources
  common/src/main/java/com/linecorp/centraldogma/common/MergeQuery.java
  common/src/main/java/com/linecorp/centraldogma/internal/Jackson.java
  it/src/test/java/com/linecorp/centraldogma/it/MergeFileTest.java
Labels: defect

#558 Update frontend dependencies
  server-auth/webapp/yarn.lock
Labels: dependencies

#559 Add GitHub Actions and remove Travis CI
  .github/workflows/gradle.yml
  .travis.yml
Labels: cleanup

#561 Update Armeria to 1.5.0
  dependencies.yml
Labels: dependencies
