Repository line/centraldogma, pull requests merged in 2021-08, with the labels that each got.

#620 Remove MigrationUtil
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MigrationUtil.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MigrationUtilTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MissingRepositoryMetadataTest.java
Labels: cleanup

#621 Prohibit mirroring to internal repositories
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
Labels: defect

#624 Prevent access to the internal repositories from normal users
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/Project.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/ProjectUtil.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/Replica.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MissingRepositoryMetadataTest.java
Labels: improvement

#630 Add a GitHub Action for building and publishing Docker image
  .github/workflows/docker.yml
  .post-release-msg
Labels: cleanup

#632 Update dependencies
  build.gradle
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogmaBuilder.java
  dependencies.yml
Labels: dependencies
