Repository line/centraldogma, pull requests merged in 2021-05, with the labels that each got.

#591 Replace some usages of TemporaryFolderExtension
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryManagerWrapperTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitGcRevisionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManagerTest.java
Labels: cleanup

#593 Update dependencies
  .github/workflows/gradle.yml
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
  client/java-armeria/src/test/resources/centraldogma-profiles-test.json
  dependencies.yml
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  settings/checkstyle/checkstyle.xml
Labels: dependencies

#589 Use a blocking task executor for the watch callacks of Central Dogma client
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaBuilder.java
  client/java-armeria-legacy/src/test/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogmaTest.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/AbstractArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java/build.gradle
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/TransformingWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/client/Watcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/AbstractWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/FileWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/RepositoryWatcher.java
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
  it/src/test/java/com/linecorp/centraldogma/it/updater/CentralDogmaBeanTest.java
Labels: defect

#598 Update dependencies
  build.gradle
  dependencies.yml
  dist/build.gradle
  server-auth/webapp/build.gradle
Labels: dependencies

#592 Build Windows and macOS on GitHub Actions
  .appveyor.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/scripts/lib/common-git.gradle
  it/src/test/java/com/linecorp/centraldogma/it/WriteQuotaTestBase.java
Labels: cleanup

#602 Change the service name of watch API calls
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/test/java/com/linecorp/centraldogma/server/MetricsTest.java
Labels: improvement
