Repository line/centraldogma, pull requests merged in 2021-12, with the labels that each got.

#644 Fix flaky test in CentralDogmaEndpointGroupTest
  it/src/test/java/com/linecorp/centraldogma/it/CentralDogmaEndpointGroupTest.java
Labels: cleanup

#652 Update dependencies
  dependencies.yml
Labels: dependencies

#646 Peel exceptions before handling
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
Labels: defect

#653 Throw error that entries are not found on watching if want
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/WatchConstants.java
  client/java/src/main/java/com/linecorp/centraldogma/client/Watcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/AbstractWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/FileWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/RepositoryWatcher.java
  client/java/src/test/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogmaTest.java
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
Labels: new feature

#645 Add file exclusion rule for mirroring
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/CentralDogmaMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/Mirror.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirrorTest.java
  site/src/sphinx/mirroring.rst
Labels: breaking change, new feature

#649 Disallow to create non-reserved files in internal repositories
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaTest.java
  common/src/main/java/com/linecorp/centraldogma/common/InvalidPushException.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/Converter.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
Labels: improvement

#657 Execute mapper only once when the child watcher gets notified
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/TransformingWatcherTest.java
  client/java/src/main/java/com/linecorp/centraldogma/client/TransformingWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/client/Watcher.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/AbstractWatcher.java
  it/src/test/java/com/linecorp/centraldogma/it/WatchTest.java
Labels: defect

#656 Fix `updateStatus` doesn't update replication when read-only mode
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
Labels: defect

#654 Fix to accept valid ETag values for watch API
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverter.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/WatchRequestConverterTest.java
Labels: defect
