Repository line/centraldogma, pull requests merged in 2021-03, with the labels that each got.

#567 Add metadata only once for a repository
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
Labels: defect

#564 Run git gc periodically
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/RepositoryGarbageCollectionConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/RepositoryGarbageCollectionPlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitGcRevision.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/main/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/RepositoryGarbageCollectionPluginTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitGcRevisionTest.java
  site/src/sphinx/setup-configuration.rst
Labels: improvement

#568 Normalize chagnes and commit in the same lock when pushing
  common/src/main/java/com/linecorp/centraldogma/common/DefaultChange.java
  server/src/jmh/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryBenchmark.java
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractPushCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandType.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommitResult.java
  server/src/main/java/com/linecorp/centraldogma/server/command/NormalizingPushCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/PushAsIsCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ReplicationLog.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositorySupport.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/command/PushAsIsCommandTest.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ReplicationLogTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperQuotaTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitIdDatabaseTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
Labels: defect, improvement
