Repository line/centraldogma, pull requests merged in 2021-04, with the labels that each got.

#566 Fix code example for CentralDogma#repositoryWatcher
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
Labels: cleanup

#571 Add a lock timeout for ZooKeeperCommandExecutor
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/RepositoryGarbageCollectionPlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperQuotaTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/RepositoryGarbageCollectionPluginTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitGcTimeoutTest.java
Labels: defect

#573 Fix a bug where illegal context is pushed
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
Labels: defect

#578 Add CentralDogmaClientFactoryConfigurator
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientFactoryConfigurator.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaAutoConfigurationTest.java
  client/java-spring-boot-autoconfigure/src/test/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfigurationWithClientFactoryTest.java
Labels: breaking change, new feature

#580 Update dependencies
  dependencies.yml
  gradle/wrapper/gradle-wrapper.properties
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommandExecutor.java
Labels: dependencies

#582 Pull https://github.com/line/gradle-scripts 5282f32
  gradle/scripts/.gitrepo
  gradle/scripts/lib/common-dependencies.gradle
  gradle/scripts/lib/common-git.gradle
  gradle/scripts/lib/java-coverage.gradle
  gradle/scripts/lib/java-javadoc.gradle
  gradle/scripts/lib/java-rpc-proto.gradle
  gradle/scripts/lib/java-rpc-thrift.gradle
  gradle/scripts/lib/java.gradle
  gradle/scripts/lib/thrift/0.14/thrift.linux-x86_64
  gradle/scripts/lib/thrift/0.14/thrift.osx-x86_64
  gradle/scripts/lib/thrift/0.14/thrift.windows-x86_32
  gradle/scripts/lib/thrift/0.14/thrift.windows-x86_64
  gradle/scripts/settings-flags.gradle
Labels: cleanup

#584 Add Snappy and Dropwizard metric dependency.
  dependencies.yml
  server/build.gradle
Labels: defect, dependencies

#583 Disallow creating a change of a JSON file using `Change.ofText{Upsert,Patch}
  common/src/main/java/com/linecorp/centraldogma/common/Change.java
  common/src/test/java/com/linecorp/centraldogma/common/ChangeTest.java
Labels: defect

#585 Downgrade ZooKeeper
  dependencies.yml
  server/build.gradle
Labels: dependencies
