Repository line/centraldogma, pull requests merged in 2021-06, with the labels that each got.

#604 Downgrade JMH to 0.5.3
  build.gradle
  dependencies.yml
Labels: dependencies

#606 Add missing package-info.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/package-info.java
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/package-info.java
  common/src/main/java/com/linecorp/centraldogma/common/util/NonNullByDefault.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/package-info.java
  common/src/main/java/com/linecorp/centraldogma/internal/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/util/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/package-info.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/package-info.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/package-info.java
Labels: cleanup

#611 Fails when package-info.java is missing in internal packages
  settings/checkstyle/checkstyle-suppressions.xml
Labels: cleanup

#607 Add a path from a project page to a metadata page on UI
  server/src/main/resources/webapp/i18n/en.main.json
  server/src/main/resources/webapp/scripts/app/entities/projects/project.html
Labels: new feature

#613 Update dependencies
  build.gradle
  dependencies.yml
  dist/build.gradle
Labels: dependencies
