Repository line/centraldogma, pull requests merged in 2022-02, with the labels that each got.

#679 Improve the error message of an `TimeoutException` raised by `CentralDogmaBeanFactory`
  client/java/src/main/java/com/linecorp/centraldogma/client/updater/CentralDogmaBeanFactory.java
  it/src/test/java/com/linecorp/centraldogma/it/updater/CentralDogmaBeanTest.java
Labels: improvement

#677 Update dependencies
  dependencies.yml
Labels: dependencies

#664 Add maxCommits to CentralDogma.getHistory()
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogmaRepository.java
  client/java/src/main/java/com/linecorp/centraldogma/client/HistoryRequest.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  common/src/main/java/com/linecorp/centraldogma/internal/HistoryConstants.java
  it/src/test/java/com/linecorp/centraldogma/it/CacheTest.java
  it/src/test/java/com/linecorp/centraldogma/it/FileHistoryAndDiffTest.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
Labels: new feature, deprecation

#680 Fix to set the author of a repository correctly
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
Labels: defect

#682 Add Author as a field in Repository
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitIdDatabaseTest.java
Labels: defect
