Repository line/centraldogma, pull requests merged in 2022-11, with the labels that each got.

#745 Remove gradle-log-plugin
  dependencies.toml
  dist/build.gradle
  site/src/sphinx/setup-installation.rst
Labels: cleanup

#744 Improve mirroring metrics
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTask.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
Labels: defect

#743 Update Armeria to 1.20.2
  dependencies.toml
Labels: dependencies

#746 Fix a wrong tarball name in publish-release.yml
  .github/workflows/publish-release.yml
Labels: defect

#748 Correctly copy CLI binaries to dist path
  dist/build.gradle
Labels: defect

#749 Bump Armeria to 1.20.3 from 1.20.2
  dependencies.toml
Labels: dependencies

#752 Fix equals() implementation in AbstractCommand (#751)
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommand.java
  server/src/test/java/com/linecorp/centraldogma/server/command/CreateSessionCommandTest.java
Labels: defect

#747 Update plain React with nextjs
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  webapp/.eslintrc.js
  webapp/README.md
  webapp/next-env.d.ts
  webapp/next.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/pages/_app.tsx
  webapp/pages/api/v0/security_enabled.ts
  webapp/pages/api/v0/users/me.ts
  webapp/pages/api/v1/login.ts
  webapp/pages/api/v1/logout.ts
  webapp/pages/api/v1/projects.ts
  webapp/pages/api/v1/security_enabled.ts
  webapp/pages/app/projects.tsx
  webapp/pages/web/auth/login.tsx
  webapp/public/static/favicon.ico
  webapp/src/dogma/Dogma.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/auth/util.ts
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/store.ts
  webapp/src/index.html
  webapp/src/index.tsx
  webapp/tsconfig-webpack.json
  webapp/tsconfig.json
  webapp/webpack.config.ts
Labels: improvement

#756 Copy generated static files into the `server` module
  server/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  webapp/build.gradle
  webapp/next.config.js
  webapp/package.json
  webapp/pages/index.tsx
  webapp/pages/web/auth/login.tsx
Labels: new feature

#758 Add a trailing slash to the auth URLs
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthProvider.java
  webapp/src/dogma/features/auth/Authorized.tsx
Labels: defect

#757 Add more setup to integrate the webapp with the test server
  webapp/build.gradle
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/pages/_app.tsx
  webapp/src/pages/api/v0/security_enabled.ts
  webapp/src/pages/api/v0/users/me.ts
  webapp/src/pages/api/v1/login.ts
  webapp/src/pages/api/v1/logout.ts
  webapp/src/pages/api/v1/projects.ts
  webapp/src/pages/api/v1/security_enabled.ts
  webapp/src/pages/app/projects.tsx
  webapp/src/pages/index.tsx
  webapp/src/pages/web/auth/login.tsx
Labels: cleanup

#759 Make a Next.js test app login with a Central Dogma server
  .gitignore
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthProvider.java
  webapp/build.gradle
  webapp/next.config.js
  webapp/src/dogma/features/auth/Authorized.tsx
Labels: improvement

#760 Decouple authentication routes from authorization routes
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthProvider.java
  webapp/build.gradle
  webapp/package-lock.json
  webapp/package.json
  webapp/src/dogma/common/components/Deferred.tsx
  webapp/src/dogma/common/components/Layout.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/auth/LoginForm.tsx
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/auth/util.ts
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/pages/app/projects.tsx
  webapp/src/pages/web/auth/login.tsx
Labels: improvement

#761 Display client error
  webapp/src/dogma/common/components/ErrorWrapper.tsx
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/auth/util.ts
  webapp/src/dogma/features/message/messageSlice.ts
  webapp/src/dogma/features/services/ErrorHandler.ts
  webapp/src/dogma/store.ts
  webapp/src/pages/_app.tsx
Labels: new feature

#762 Exclude ZooKeeper from Curator
  dependencies.toml
Labels: cleanup

#763 Setup unit testing
  webapp/.eslintrc.js
  webapp/__tests__/pages/index.test.tsx
  webapp/build.gradle
  webapp/jest.config.js
  webapp/jest.setup.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/pages/index.tsx
  webapp/tsconfig.jest.json
  webapp/tsconfig.json
Labels: improvement
