Repository line/centraldogma, pull requests merged in 2022-10, with the labels that each got.

#716 Migrate `dependencies.yml` to `dependencies.toml`
  .github/workflows/ci.yml
  .github/workflows/publish-docker.yml
  build.gradle
  client/java-armeria-legacy/build.gradle
  client/java-armeria/build.gradle
  client/java-spring-boot-autoconfigure/build.gradle
  client/java-spring-boot-starter/build.gradle
  client/java-spring-boot1-autoconfigure/build.gradle
  client/java-spring-boot1-starter/build.gradle
  client/java/build.gradle
  common-legacy/build.gradle
  common/build.gradle
  dependencies.toml
  dependencies.yml
  dist/build.gradle
  gradle/scripts/.gitrepo
  gradle/scripts/README.md
  gradle/scripts/lib/bom.gradle
  gradle/scripts/lib/common-dependencies.gradle
  it/build.gradle
  server-auth/saml/build.gradle
  server-auth/shiro/build.gradle
  server-auth/webapp/build.gradle
  server/build.gradle
  site/build.gradle
  site/src/sphinx/conf.py
  testing-internal/build.gradle
  testing/junit/build.gradle
  testing/junit4/build.gradle
Labels: cleanup

#725 Improve documentation for the PathPattern.java
  common/src/main/java/com/linecorp/centraldogma/common/PathPattern.java
Labels: documentation

#723 Automatically publish artifacts and site when a new version is released
  .github/workflows/publish-release.yml
  .github/workflows/publish-site.yml
  .post-release-msg
  site/build.gradle
Labels: miscellaneous

#728 Update dependencies
  dependencies.toml
Labels: dependencies

#729 Add Nexus plugin
  build.gradle
  dependencies.toml
Labels: cleanup

#730 Update Armeria to 1.20.1
  dependencies.toml
Labels: dependencies

#733 Increase the Git timeout of GitMirror to 60 seconds
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitMirror.java
Labels: defect

#732 Fix flaky test in `ZooKeeperQuotaTest`
  .github/workflows/actions_build.yml
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperQuotaTest.java
Labels: cleanup

#737 Make a server unhealthy when it is about to shut down.
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/test/java/com/linecorp/centraldogma/server/HealthCheckServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtilTest.java
Labels: defect

#735 Add metrics for mirroring
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTask.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirrorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTestUtils.java
Labels: improvement

#717 Support local-to-remote mirroring
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/LocalToRemoteGitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorState.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorUtil.java
  site/src/sphinx/concepts.rst
  site/src/sphinx/mirroring.rst
  site/src/sphinx/setup-configuration.rst
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/TestUtil.java
Labels: new feature
