Repository line/centraldogma, pull requests merged in 2023-09, with the labels that each got.

#874 Record metrics when INIT revision or an old revision is used
  common/build.gradle
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTask.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/test/java/com/linecorp/centraldogma/server/MetricsTest.java
Labels: miscellaneous

#876 Fix Bouncy Castle version conflict in SAML module
  server-auth/saml/build.gradle
Labels: dependencies

#878 Reuse BouncyCastleRandom
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitWithAuth.java
Labels: defect

#881 Check remote revision before fetching when mirroring
  dist/src/conf/logback.xml
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitMirrorProvider.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitWithAuth.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirror.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/GitMirrorTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
Labels: improvement

#884 Try to configure authentication for command from `GitWithAuth`
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitWithAuth.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirror.java
Labels: cleanup

#885 Close an SSH session when an auth fails
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirror.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
Labels: defect

#883 Provide a way to configure server for a plugin
  it/server/src/test/java/com/linecorp/centraldogma/it/AllReplicasPluginTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/TestAllReplicasPlugin.java
  it/server/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/AllReplicasPlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/Plugin.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginContext.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginInitContext.java
Labels: new feature
