Repository line/centraldogma, pull requests merged in 2023-02, with the labels that each got.

#795 Add create new file
  webapp/src/dogma/common/components/NewFile.tsx
  webapp/src/dogma/common/components/NewFileForm.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/file/FileList.tsx
  webapp/src/pages/api/v1/projects/[projectName]/repos/[repoName]/contents/[...fileName].ts
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/list/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/new_file/head.tsx
Labels: new feature

#796 Add file modification
  webapp/__tests__/dogma/feature/file/FileList.test.tsx
  webapp/src/dogma/common/components/CommitForm.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/common/components/NewFile.tsx
  webapp/src/dogma/common/components/editor/DeleteFileModal.tsx
  webapp/src/dogma/common/components/editor/DiscardChangesModal.tsx
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/file/FileList.tsx
  webapp/src/dogma/features/history/HistoryList.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/list/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/new_file/head/[[...path]].tsx
Labels: new feature

#790 Set authenticated user to print it in access logs
  dependencies.toml
  dist/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/AuthUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/SessionTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
Labels: new feature

#799 Upgrade dependencies for 0.60.0
  dependencies.toml
Labels: dependencies

#798 Add token operation
  webapp/src/dogma/common/components/NewToken.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/token/ActivateToken.tsx
  webapp/src/dogma/features/token/DeactivateToken.tsx
  webapp/src/dogma/features/token/DeleteToken.tsx
  webapp/src/dogma/features/token/DisplaySecretModal.tsx
  webapp/src/dogma/features/token/NewToken.tsx
  webapp/src/dogma/features/token/SecretWrapper.tsx
  webapp/src/pages/app/settings/tokens.tsx
Labels: new feature

#802 Allow to set ZooKeeper quorumListenOnAllIPs
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/ZooKeeperReplicationConfigTest.java
  site/src/sphinx/setup-configuration.rst
Labels: improvement

#803 Upgrade dependencies for 0.60.1
  dependencies.toml
Labels: dependencies

#800 Revamp projects
  webapp/__tests__/dogma/feature/repo/RepoMemberList.test.tsx
  webapp/src/dogma/common/components/CommitForm.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/common/components/UserRole.tsx
  webapp/src/dogma/common/components/editor/DiscardChangesModal.tsx
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/common/components/editor/JsonPathLegend.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/file/NewFile.tsx
  webapp/src/dogma/features/project/DeleteProject.tsx
  webapp/src/dogma/features/project/NewProject.tsx
  webapp/src/dogma/features/project/ProjectDto.ts
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/project/RestoreProject.tsx
  webapp/src/dogma/features/repo/ConfirmAddMember.tsx
  webapp/src/dogma/features/repo/DeleteMember.tsx
  webapp/src/dogma/features/repo/DeleteRepo.tsx
  webapp/src/dogma/features/repo/DeleteRepoMemberDto.ts
  webapp/src/dogma/features/repo/NewMember.tsx
  webapp/src/dogma/features/repo/NewRepo.tsx
  webapp/src/dogma/features/repo/RepoList.tsx
  webapp/src/dogma/features/repo/RepoMemberList.tsx
  webapp/src/dogma/features/repo/RepoMetaList.tsx
  webapp/src/dogma/features/repo/RestoreRepo.tsx
  webapp/src/pages/api/v1/projects/index.ts
  webapp/src/pages/app/projects/[projectName]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/new_file/head/[[...path]].tsx
  webapp/src/pages/app/projects/index.tsx
  webapp/src/pages/app/projects/metadata/[projectName]/index.tsx
Labels: new feature

#805 Add project token mutation
  webapp/__tests__/dogma/feature/repo/RepoTokenList.test.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/history/HistoryList.tsx
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/repo/AppTokenList.tsx
  webapp/src/dogma/features/repo/ConfirmAddToken.tsx
  webapp/src/dogma/features/repo/NewAppToken.tsx
  webapp/src/pages/app/projects/[projectName]/index.tsx
  webapp/src/pages/app/projects/metadata/[projectName]/index.tsx
  webapp/src/pages/app/settings/tokens.tsx
Labels: new feature

#806 Add update repository permissions
  webapp/README.md
  webapp/__tests__/dogma/feature/repo/RepoPermissionList.test.tsx
  webapp/src/dogma/common/components/MetadataButton.tsx
  webapp/src/dogma/common/components/table/Filter.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/metadata/AppMemberDto.ts
  webapp/src/dogma/features/metadata/AppMemberList.tsx
  webapp/src/dogma/features/metadata/AppTokenDto.ts
  webapp/src/dogma/features/metadata/AppTokenList.tsx
  webapp/src/dogma/features/metadata/ConfirmAddMember.tsx
  webapp/src/dogma/features/metadata/ConfirmAddToken.tsx
  webapp/src/dogma/features/metadata/DeleteMember.tsx
  webapp/src/dogma/features/metadata/DeleteMemberDto.ts
  webapp/src/dogma/features/metadata/NewAppToken.tsx
  webapp/src/dogma/features/metadata/NewMember.tsx
  webapp/src/dogma/features/metadata/RepoMetaList.tsx
  webapp/src/dogma/features/project/ProjectMetadataDto.ts
  webapp/src/dogma/features/repo/RepoMemberDto.ts
  webapp/src/dogma/features/repo/RepoPermissionDto.ts
  webapp/src/dogma/features/repo/RepoPermissionList.tsx
  webapp/src/dogma/features/repo/permissions/AddUserPermissionDto.ts
  webapp/src/dogma/features/repo/permissions/ConfirmAddUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmUpdateRolePermission.tsx
  webapp/src/dogma/features/repo/permissions/DeleteUserPermissionDto.ts
  webapp/src/dogma/features/repo/permissions/NewRepoTokenPermission.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/RolePermissionForm.tsx
  webapp/src/dogma/features/repo/permissions/UserPermission.tsx
  webapp/src/pages/app/projects/[projectName]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/edit.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/list/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/metadata/[projectName]/[repoName].tsx
  webapp/src/pages/app/projects/metadata/[projectName]/index.tsx
Labels: new feature
