Repository line/centraldogma, pull requests merged in 2023-12, with the labels that each got.

#901 Fix to access for a member to the meta repository.
  it/server/src/test/java/com/linecorp/centraldogma/it/NonRandomTokenTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/ReplicationWriteQuotaTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/StandaloneWriteQuotaTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataApiServiceTest.java
Labels: defect

#871 Use personal acesss token to trigger CI builds
  .github/workflows/update-armeria-version.yml
Labels: miscellaneous

#900 Add replication log details to the exception message when replaying ZooKeeper log fails.
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: improvement
