Repository line/centraldogma, pull requests merged in 2023-06, with the labels that each got.

#844 Publish a docker image when a new tag is created
  .github/workflows/publish-docker.yml
Labels: miscellaneous

#839 Do not read user SSH config / Fix GitMirrorAuthTest
  server-jgit6/src/main/java/com/linecorp/centraldogma/server/internal/mirror/Git6WithAuth.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/Git5WithAuth.java
Labels: defect

#848 Fix failure to render plantuml
  .github/workflows/publish-site.yml
Labels: documentation

#850 Bump `armeria` to 1.24.2
  dependencies.toml
Labels: dependencies
