Repository line/centraldogma, pull requests merged in 2023-04, with the labels that each got.

#831 Update Central Dogma CLI to 0.1.0
  dist/build.gradle
  dist/src/bin/dogma
Labels: dependencies

#818 Display the original commit message when mirroring
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitMirror.java
Labels: improvement

#828 Migrate Docker registry from Docker Hub to GitHub container registry
  .github/workflows/publish-docker.yml
  dist/build.gradle
  gradle/scripts/.gitrepo
  gradle/scripts/lib/java.gradle
  gradle/scripts/settings-flags.gradle
Labels: breaking change

#832 Update dependencies
  dependencies.toml
Labels: dependencies

#834 Fix incorrect `spring-boot` artifact name
  build.gradle
  site/src/sphinx/client-java.rst
  site/src/sphinx/setup-installation.rst
Labels: documentation

#835 Remove JGit 5 dependencies when building server
  dist/build.gradle
Labels: defect

#837 Do not run auto-GC against any repositories
  it/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/IsolatedSystemReader.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/JGitUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitWithAuth.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/IsolatedSystemReaderTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
  testing/junit/src/main/java/com/linecorp/centraldogma/testing/junit/CentralDogmaExtension.java
Labels: defect
