Repository line/centraldogma, pull requests merged in 2024-09, with the labels that each got.

#1033 Fix that the created group is not watched by XdsResourceWatchingService
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceWatchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsResourceWatchingServiceTest.java
Labels: defect

#1034 Add `ManagementService`
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/ManagementConfig.java
  server/src/test/java/com/linecorp/centraldogma/server/ManagementServiceTest.java
  site/src/sphinx/setup-configuration.rst
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
Labels: new feature

#1030 Remove hostnamePatterns from credential files
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationServiceClusterTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationServiceTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/RemovingHostnamePatternsServiceTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/RemovingHostnamePatternsService.java
Labels: improvement
