Repository line/centraldogma, pull requests merged in 2024-07, with the labels that each got.

#966 Fix to read all short words for the mirror migration
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationServiceClusterTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationServiceTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationService.java
Labels: defect

#838 Add Mirroring and Credential UI
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringAndCredentialServiceV1Test.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/CredentialServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/credential/PublicKeyMirrorCredentialTest.java
  settings.gradle
  webapp/.eslintrc.js
  webapp/__tests__/dogma/feature/history/HistoryList.test.tsx
  webapp/__tests__/dogma/feature/repo/RepoPermissionList.test.tsx
  webapp/build.gradle
  webapp/package-lock.json
  webapp/package.json
  webapp/src/dogma/common/components/Breadcrumbs.tsx
  webapp/src/dogma/common/components/LabelledIcon.tsx
  webapp/src/dogma/common/components/Layout.tsx
  webapp/src/dogma/common/components/form/FieldErrorMessage.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/credential/CredentialDto.ts
  webapp/src/dogma/features/credential/CredentialForm.tsx
  webapp/src/dogma/features/credential/CredentialList.tsx
  webapp/src/dogma/features/credential/CredentialView.tsx
  webapp/src/dogma/features/history/HistoryList.tsx
  webapp/src/dogma/features/metadata/ProjectMetadataView.tsx
  webapp/src/dogma/features/metadata/RepoMetaList.tsx
  webapp/src/dogma/features/mirror/MirrorDto.ts
  webapp/src/dogma/features/mirror/MirrorForm.tsx
  webapp/src/dogma/features/mirror/MirrorList.tsx
  webapp/src/dogma/features/mirror/MirrorView.tsx
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/repo/RepoPermissionList.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoTokenPermission.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/RolePermissionForm.tsx
  webapp/src/pages/_app.tsx
  webapp/src/pages/api/v1/projects/[projectName]/credentials/[index]/index.ts
  webapp/src/pages/api/v1/projects/[projectName]/credentials/index.ts
  webapp/src/pages/api/v1/projects/[projectName]/mirrors/[index]/index.ts
  webapp/src/pages/api/v1/projects/[projectName]/mirrors/index.ts
  webapp/src/pages/app/projects/[projectName]/credentials/[id]/edit/index.tsx
  webapp/src/pages/app/projects/[projectName]/credentials/[id]/index.tsx
  webapp/src/pages/app/projects/[projectName]/credentials/index.tsx
  webapp/src/pages/app/projects/[projectName]/credentials/new/index.tsx
  webapp/src/pages/app/projects/[projectName]/index.tsx
  webapp/src/pages/app/projects/[projectName]/members/index.tsx
  webapp/src/pages/app/projects/[projectName]/metadata/index.tsx
  webapp/src/pages/app/projects/[projectName]/mirrors/[id]/edit/index.tsx
  webapp/src/pages/app/projects/[projectName]/mirrors/[id]/index.tsx
  webapp/src/pages/app/projects/[projectName]/mirrors/index.tsx
  webapp/src/pages/app/projects/[projectName]/mirrors/new/index.tsx
  webapp/src/pages/app/projects/[projectName]/permissions/index.tsx
  webapp/src/pages/app/projects/[projectName]/permissions/repos/[repoName]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/list/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/tokens/index.tsx
  webapp/src/pages/app/projects/metadata/[projectName]/index.tsx
  webapp/src/test/java/com/linecorp/centraldogma/webapp/ShiroCentralDogmaTestServer.java
  webapp/src/test/java/com/linecorp/centraldogma/webapp/SimpleCentralDogmaTestServer.java
Labels: new feature

#970 Update dependencies
  webapp/.eslintrc.js
  webapp/__tests__/dogma/feature/history/HistoryList.test.tsx
  webapp/build.gradle
  webapp/jest.config.js
  webapp/jest.polyfills.js
  webapp/jest.setup.js
  webapp/next.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/dogma/common/components/CommitForm.tsx
  webapp/src/dogma/common/components/Deferred.tsx
  webapp/src/dogma/common/components/editor/DeleteFileModal.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/credential/CredentialForm.tsx
  webapp/src/dogma/features/credential/CredentialList.tsx
  webapp/src/dogma/features/file/NewFile.tsx
  webapp/src/dogma/features/metadata/ConfirmAddMember.tsx
  webapp/src/dogma/features/metadata/ConfirmAddToken.tsx
  webapp/src/dogma/features/mirror/MirrorForm.tsx
  webapp/src/dogma/features/mirror/MirrorList.tsx
  webapp/src/dogma/features/project/NewProject.tsx
  webapp/src/dogma/features/repo/NewRepo.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmAddUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmUpdateRolePermission.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoTokenPermission.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/UserPermission.tsx
  webapp/src/dogma/features/token/ActivateToken.tsx
  webapp/src/dogma/features/token/DeactivateToken.tsx
  webapp/src/dogma/features/token/NewToken.tsx
  webapp/src/pages/app/projects/[projectName]/credentials/[id]/index.tsx
Labels: dependencies

#971 Format code with Prettier
  webapp/.prettierignore
  webapp/__tests__/dogma/feature/history/HistoryList.test.tsx
  webapp/build.gradle
  webapp/package.json
  webapp/src/dogma/common/components/Breadcrumbs.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/credential/CredentialForm.tsx
  webapp/src/dogma/features/credential/CredentialView.tsx
  webapp/src/dogma/features/history/HistoryList.tsx
  webapp/src/dogma/features/mirror/MirrorForm.tsx
  webapp/src/dogma/features/mirror/MirrorView.tsx
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmAddUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoTokenPermission.tsx
  webapp/src/dogma/features/repo/permissions/NewRepoUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/RolePermissionForm.tsx
  webapp/src/dogma/features/repo/permissions/UserPermission.tsx
  webapp/src/pages/api/v1/projects/[projectName]/credentials/[index]/index.ts
  webapp/src/pages/app/projects/[projectName]/credentials/[id]/index.tsx
  webapp/src/pages/app/projects/[projectName]/index.tsx
Labels: cleanup

#972 Welcome page
  webapp/__tests__/pages/index.test.tsx
  webapp/jest.setup.js
  webapp/next.config.js
  webapp/package.json
  webapp/src/dogma/StoreProvider.tsx
  webapp/src/dogma/common/components/CommitForm.tsx
  webapp/src/dogma/common/components/ErrorWrapper.tsx
  webapp/src/dogma/common/components/Layout.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/common/components/editor/DeleteFileModal.tsx
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/auth/LoginForm.tsx
  webapp/src/dogma/features/credential/CredentialView.tsx
  webapp/src/dogma/features/file/NewFile.tsx
  webapp/src/dogma/features/metadata/ConfirmAddMember.tsx
  webapp/src/dogma/features/metadata/ConfirmAddToken.tsx
  webapp/src/dogma/features/metadata/DeleteMember.tsx
  webapp/src/dogma/features/metadata/ProjectMetadataView.tsx
  webapp/src/dogma/features/mirror/MirrorForm.tsx
  webapp/src/dogma/features/project/DeleteProject.tsx
  webapp/src/dogma/features/project/NewProject.tsx
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/project/RestoreProject.tsx
  webapp/src/dogma/features/repo/DeleteRepo.tsx
  webapp/src/dogma/features/repo/NewRepo.tsx
  webapp/src/dogma/features/repo/RestoreRepo.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmAddUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmUpdateRolePermission.tsx
  webapp/src/dogma/features/services/ErrorHandler.ts
  webapp/src/dogma/features/token/ActivateToken.tsx
  webapp/src/dogma/features/token/DeactivateToken.tsx
  webapp/src/dogma/features/token/DeleteToken.tsx
  webapp/src/dogma/features/token/DisplaySecretModal.tsx
  webapp/src/dogma/features/token/NewToken.tsx
  webapp/src/dogma/features/token/SecretWrapper.tsx
  webapp/src/dogma/hooks.ts
  webapp/src/dogma/store.ts
  webapp/src/dogma/util/test-utils.tsx
  webapp/src/pages/_app.tsx
  webapp/src/pages/app/projects/[projectName]/credentials/[id]/edit/index.tsx
  webapp/src/pages/app/projects/[projectName]/credentials/new/index.tsx
  webapp/src/pages/app/projects/[projectName]/mirrors/[id]/edit/index.tsx
  webapp/src/pages/app/projects/[projectName]/mirrors/new/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/list/[revision]/[[...path]]/index.tsx
  webapp/src/pages/index.tsx
  webapp/src/pages/web/auth/login.tsx
Labels: new feature

#974 Beautify login form
  webapp/next.config.js
  webapp/public/central_dogma.png
  webapp/src/dogma/features/auth/LoginForm.tsx
Labels: improvement

#973 Allow adding `@` prefix for internal projects
  common/src/main/java/com/linecorp/centraldogma/internal/Util.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectApiManager.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1ListProjectTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
Labels: improvement

#967 Wait for internal projects to be created before starting the mirror migration
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationServiceTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/PluginGroup.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/InternalProjectInitializer.java
Labels: defect

#965 Change xDS resource directory structure
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMetaRepositoryWithMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableMultiDiffCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryManager.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/InternalProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/DiffResultType.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/CentralDogmaSnapshotResources.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/CentralDogmaXdsResources.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CentralDogmaSnapshotResourcesTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/DiscoveryServiceItTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/LdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsTestUtil.java
Labels: improvement

#978 Apply maintainers feedback
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringAndCredentialServiceV1Test.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/CredentialServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/AccessTokenMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/NoneMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/PasswordMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/credential/PublicKeyMirrorCredential.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorCredential.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/credential/MirrorCredentialTest.java
  webapp/src/dogma/common/components/CommitForm.tsx
  webapp/src/dogma/common/components/Deferred.tsx
  webapp/src/dogma/common/components/Footer.tsx
  webapp/src/dogma/common/components/Layout.tsx
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/common/components/NotificationWrapper.tsx
  webapp/src/dogma/common/components/ProjectSettingsButton.tsx
  webapp/src/dogma/common/components/editor/DeleteFileModal.tsx
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/ProjectRole.tsx
  webapp/src/dogma/features/auth/UserDto.ts
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/file/NewFile.tsx
  webapp/src/dogma/features/message/messageSlice.ts
  webapp/src/dogma/features/notification/notificationSlice.ts
  webapp/src/dogma/features/project/DeleteProject.tsx
  webapp/src/dogma/features/project/NewProject.tsx
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/project/RestoreProject.tsx
  webapp/src/dogma/features/project/settings/ProjectSettingsView.tsx
  webapp/src/dogma/features/project/settings/credentials/CredentialForm.tsx
  webapp/src/dogma/features/project/settings/credentials/CredentialView.tsx
  webapp/src/dogma/features/project/settings/members/AppMemberList.tsx
  webapp/src/dogma/features/project/settings/members/ConfirmAddMember.tsx
  webapp/src/dogma/features/project/settings/members/DeleteMember.tsx
  webapp/src/dogma/features/project/settings/mirrors/MirrorForm.tsx
  webapp/src/dogma/features/project/settings/tokens/ConfirmAddToken.tsx
  webapp/src/dogma/features/repo/DeleteRepo.tsx
  webapp/src/dogma/features/repo/NewRepo.tsx
  webapp/src/dogma/features/repo/RestoreRepo.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmAddUserPermission.tsx
  webapp/src/dogma/features/repo/permissions/ConfirmUpdateRolePermission.tsx
  webapp/src/dogma/features/services/ErrorHandler.ts
  webapp/src/dogma/features/services/ErrorMessageParser.ts
  webapp/src/dogma/features/token/ActivateToken.tsx
  webapp/src/dogma/features/token/DeactivateToken.tsx
  webapp/src/dogma/features/token/DeleteToken.tsx
  webapp/src/dogma/features/token/DisplaySecretModal.tsx
  webapp/src/dogma/features/token/NewToken.tsx
  webapp/src/dogma/features/token/SecretWrapper.tsx
  webapp/src/dogma/store.ts
  webapp/src/pages/_app.tsx
  webapp/src/pages/app/projects/[projectName]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/tree/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/credentials/[id]/edit/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/credentials/new/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/mirrors/[id]/edit/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/mirrors/new/index.tsx
  webapp/src/test/java/com/linecorp/centraldogma/webapp/ShiroCentralDogmaTestServer.java
Labels: improvement

#969 Clean up HTTP service configuration with new Armeria API
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/UserService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AbstractService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/CredentialServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
Labels: cleanup

#983 Parse text to JSON before committing content in an editor
  webapp/src/dogma/common/components/CommitForm.tsx
  webapp/src/dogma/features/file/NewFile.tsx
Labels: defect

#992 Remove `:server-auth:webapp`
  server-auth/webapp/build.gradle
  server-auth/webapp/package-lock.json
  server-auth/webapp/package.json
  server-auth/webapp/public/index.html
  server-auth/webapp/src/App.css
  server-auth/webapp/src/App.tsx
  server-auth/webapp/src/LoginForm.tsx
  server-auth/webapp/src/LogoutForm.tsx
  server-auth/webapp/src/central_dogma.png
  server-auth/webapp/src/index.css
  server-auth/webapp/src/index.tsx
  server-auth/webapp/src/react-app-env.d.ts
  server-auth/webapp/tsconfig-webpack.json
  server-auth/webapp/tsconfig.json
  server-auth/webapp/tslint.json
  server-auth/webapp/webpack.config.ts
  server/build.gradle
  settings.gradle
  webapp/README.md
Labels: cleanup

#991 Correctly log elapsed milliseconds in `CentralDogmaBeanFactory`
  client/java/src/main/java/com/linecorp/centraldogma/client/updater/CentralDogmaBeanFactory.java
Labels: defect

#990 Syntax highlighting for well known configuration files
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
Labels: improvement

#994 Do not use a global cache for Node.js
  server/build.gradle
  webapp/build.gradle
Labels: cleanup

#996 Add JsonProperty to ControlPlanePluginConfig constructor parameter
  .github/workflows/actions_build.yml
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePluginConfig.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/ControlPlanePluginConfigTest.java
Labels: defect

#1000 Fix to fetch the file content with revision
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
Labels: defect

#998 Wait for all Armeria artifacts before sending an upgrade PR
  .github/workflows/update-armeria-version.yml
Labels: miscellaneous

#1001 Set up e2e with Playwright
  webapp/.gitignore
  webapp/build.gradle
  webapp/e2e/landing.spec.ts
  webapp/jest.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/playwright.config.ts
  webapp/tests/dogma/common/components/Breadcrumbs.test.tsx
  webapp/tests/dogma/feature/file/FileList.test.tsx
  webapp/tests/dogma/feature/history/HistoryList.test.tsx
  webapp/tests/dogma/feature/repo/RepoList.test.tsx
  webapp/tests/dogma/feature/repo/RepoPermissionList.test.tsx
  webapp/tests/pages/index.test.tsx
Labels: miscellaneous
