Repository line/centraldogma, pull requests merged in 2024-06, with the labels that each got.

#961 Update dependencies
  build.gradle
  dependencies.toml
  server/build.gradle
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/GitHttpService.java
  server/src/test/java/com/linecorp/centraldogma/server/MetricsTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/GitHttpServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/Replica.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
Labels: dependencies

#957 Disallow creating a repository with a .git suffix
  common/src/main/java/com/linecorp/centraldogma/internal/Util.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CreateRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/DirectoryBasedStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
Labels: defect

#949 Fix flaky ServerStatusManagerIntegrationTest (2)
  server/src/test/java/com/linecorp/centraldogma/server/management/ServerStatusManagerIntegrationTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaReplicationExtension.java
Labels: cleanup
