Repository line/centraldogma, pull requests merged in 2024-10, with the labels that each got.

#1043 Run CI only on line/centraldogma
  .github/workflows/actions_build.yml
  .github/workflows/publish-docker.yml
Labels: cleanup

#1038 Support OAuth Token for Kubernetes Authentication via Credential Service
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/credential/AbstractCredential.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
  xds/src/main/proto/centraldogma/xds/k8s/v1/xds_kubernetes.proto
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
Labels: new feature

#1042 Fix code completion for centraldogma.initialization-timeout-millis
  client/java-spring-boot3-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaClientAutoConfiguration.java
  client/java-spring-boot3-autoconfigure/src/main/java/com/linecorp/centraldogma/client/spring/CentralDogmaSettings.java
Labels: defect

#1040 Improve the robustness of old ZooKeeper log removal
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: defect
