Repository line/centraldogma, pull requests merged in 2024-05, with the labels that each got.

#952 Restrict prefix value in `CentralDogmaConfig`
  it/server/src/test/java/com/linecorp/centraldogma/it/ConfigValueConverterTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/InvalidConfigValueConverter.java
  it/server/src/test/java/com/linecorp/centraldogma/it/ValidConfigValueConverter.java
  it/server/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.ConfigValueConverter
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
Labels: defect

#953 Add a metric for tracking the number of pushes
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/PushMetricTest.java
Labels: new feature

#923 Update the default config as document
  dist/src/conf/dogma.json
Labels: cleanup

#954 Support Git clone over HTTP in Central Dogma.
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/GitHttpService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectApiManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/GitHttpServiceTest.java
Labels: new feature
