Repository line/centraldogma, pull requests merged in 2024-02, with the labels that each got.

#812 Slow delete token
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Token.java
  server/src/main/resources/webapp/scripts/app/settings/tokens/tokens.html
  server/src/main/resources/webapp/scripts/components/entities/settings.service.js
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
Labels: defect

#909 Fix to show project creators correctly
  benchmarks/jmh/src/jmh/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryBenchmark.java
  common/src/main/java/com/linecorp/centraldogma/common/Author.java
  common/src/test/java/com/linecorp/centraldogma/common/AuthorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/UserAndTimestamp.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/Project.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
Labels: defect

#907 Enable admin access to the internal `dogma` project.
  it/server/src/test/java/com/linecorp/centraldogma/it/ClientType.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/AuthUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/UserService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AbstractService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectApiManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/SafeProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/JacksonRequestConverterFunctionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1ListProjectTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthMessageUtil.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/auth/TestAuthProvider.java
Labels: improvement

#904 Add xDS control plane
  dependencies.toml
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginInitContext.java
  settings.gradle
  testing-internal/src/main/resources/logback-test.xml
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
  testing/junit/src/main/java/com/linecorp/centraldogma/testing/junit/CentralDogmaExtension.java
  testing/junit4/src/main/java/com/linecorp/centraldogma/testing/junit4/CentralDogmaRule.java
  xds/build.gradle
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/CentralDogmaSnapshot.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/CentralDogmaSnapshotResources.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/JsonFormatUtil.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/package-info.java
  xds/src/main/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CentralDogmaSnapshotResourcesTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/DiscoveryServiceItTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/EchoContainer.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/EnvoyContainer.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/LdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsTestUtil.java
  xds/src/test/resources/envoy/ads.config.yaml
  xds/src/test/resources/envoy/launch_envoy.sh
  xds/src/test/resources/envoy/xds.config.yaml
Labels: new feature

#875 Use strict versions for SFL4J and Logback
  build.gradle
  client/java-spring-boot3-autoconfigure/build.gradle
  dependencies.toml
  dist/build.gradle
  server/build.gradle
  testing-internal/build.gradle
Labels: cleanup

#913 Update dependencies
  dependencies.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#899 Add `AdministrativeCommand`s
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/AdministrativeCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandType.java
  server/src/main/java/com/linecorp/centraldogma/server/command/ForcePushCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/UpdateServerStatusCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ReplicationLog.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
Labels: new feature

#914 Add xds module to build.gradle in dist
  dist/build.gradle
Labels: cleanup
