Repository line/centraldogma, pull requests merged in 2024-04, with the labels that each got.

#916 Bump up "ace_builds" from 1.2.5 to 1.32.2
  server/package-lock.json
  server/package.json
Labels: dependencies

#938 Wait for quiet period after health check
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/GracefulShutdownTimeout.java
  server/src/test/java/com/linecorp/centraldogma/server/CentralDogmaConfigTest.java
Labels: improvement

#929 Gracefully shut down watches when server is shutting down
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractWatcher.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  it/server/src/test/java/com/linecorp/centraldogma/it/GracefulShutdownTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
Labels: improvement

#941 Retry the ZooKeeper lock operation to avoid entering read-only mode unwantedly
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/Replica.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
Labels: defect

#943 Add `project` and `repository` tags to `api` metrics
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/PushMetricTest.java
Labels: improvement

#946 Use LinkedBlockingQueue instead of LinkedTransferQueue for ThreadPoolExecutor
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: defect

#917 [ISSUE-897] Add ANONYMOUS Permission
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/ProjectRole.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/User.java
  server/src/main/resources/webapp/i18n/en.main.json
  server/src/main/resources/webapp/scripts/app/entities/metadata/metadata.project.html
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataApiServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/PerRolePermissionsTest.java
  site/src/sphinx/auth.rst
Labels: new feature

#921 Update the whole cluster status via REST API
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogma.java
  common/src/main/java/com/linecorp/centraldogma/common/ReadOnlyException.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandExecutorStatusManager.java
  server/src/main/java/com/linecorp/centraldogma/server/command/ForwardingCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/UpdateServerStatusCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/AdministrativeService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/UpdateServerStatusRequest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/management/ServerStatus.java
  server/src/main/java/com/linecorp/centraldogma/server/management/ServerStatusManager.java
  server/src/main/java/com/linecorp/centraldogma/server/management/package-info.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/AdministrativeServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/command/CommandExecutorStatusManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/management/ServerStatusManagerIntegrationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/management/ServerStatusManagerTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaReplicationExtension.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerExtension.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/TestUtil.java
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
Labels: new feature

#945 Update dependencies
  dependencies.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#948 Fix flaky ServerStatusManagerIntegrationTest
  server/src/test/java/com/linecorp/centraldogma/server/management/ServerStatusManagerIntegrationTest.java
Labels: cleanup

#950 Revert "Add `project` and `repository` tags to `api` metrics (#943)"
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/converter/PushMetricTest.java
Labels: defect
