Repository line/centraldogma, pull requests merged in 2024-12, with the labels that each got.

#1064 Add Transforming Content Push Command
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractPushCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandType.java
  server/src/main/java/com/linecorp/centraldogma/server/command/ContentTransformer.java
  server/src/main/java/com/linecorp/centraldogma/server/command/NormalizableCommit.java
  server/src/main/java/com/linecorp/centraldogma/server/command/NormalizingPushCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/TransformCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/AbstractChangesApplier.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DefaultChangesApplier.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/TransformingChangesApplier.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ReplicationLogTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
Labels: new feature

#1067 Add reportFailedTest
  .github/workflows/actions_build.yml
  build.gradle
  dependencies.toml
Labels: cleanup

#1066 Clear Filter Value When Clicking on a Directory in the File List View
  webapp/src/dogma/features/file/FileList.tsx
Labels: improvement

#1065 Update dependencies
  dependencies.toml
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/AggregatingMultipleKubernetesTest.java
Labels: dependencies

#1070 Implement `LogMeta#toString` to easily debug zookeeper log removal warnings
  .github/workflows/actions_build.yml
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
Labels: improvement

#1071 Disable sphinx for aarch_64
  site/build.gradle
Labels: miscellaneous

#1062 Provide a way to pin a mirror to a zone
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/MirrorDto.java
  it/mirror-listener/src/test/java/com/linecorp/centraldogma/it/mirror/listener/CustomMirrorListenerTest.java
  it/mirror/build.gradle
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorIntegrationTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/LocalToRemoteGitMirrorTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/MirrorRunnerTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/ZoneAwareMirrorTest.java
  it/mirror/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.mirror.MirrorListener
  it/zone-leader-plugin/src/test/java/com/linecorp/centraldogma/it/zoneleader/ZoneLeaderPluginTest.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/GitMirrorProvider.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirror.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMetaRepositoryWithMirrorTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingServiceTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringAndCredentialServiceV1Test.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTestUtils.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/PluginGroup.java
  server/src/main/java/com/linecorp/centraldogma/server/ZoneConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/CentralDogmaMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorRunner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/CentralDogmaMirrorProvider.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/MirrorConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/Mirror.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorContext.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorResult.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorTask.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirroringServicePluginConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/AllReplicasPlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/Plugin.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/MetaRepository.java
  server/src/test/java/com/linecorp/centraldogma/server/PluginGroupTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/CentralDogmaMirrorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/plugin/NoopPluginForAllReplicas.java
  server/src/test/java/com/linecorp/centraldogma/server/plugin/NoopPluginForLeader.java
  site/src/sphinx/mirroring.rst
  site/src/sphinx/setup-configuration.rst
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaReplicationExtension.java
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/project/settings/mirrors/MirrorDto.ts
  webapp/src/dogma/features/project/settings/mirrors/MirrorForm.tsx
  webapp/src/dogma/features/project/settings/mirrors/MirrorView.tsx
  webapp/src/test/java/com/linecorp/centraldogma/webapp/ShiroCentralDogmaTestServer.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingPlugin.java
Labels: new feature

#1069 Refactor `MetadataService` to Use `ContentTransformer`
  common/src/main/java/com/linecorp/centraldogma/common/RedundantChangeException.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/AbstractChangesApplier.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/TransformingChangesApplier.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/ProjectMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositorySupport.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
Labels: improvement

#1073 Expose a port number of `remoteUrl` in the mirror UI
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringAndCredentialServiceV1Test.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
Labels: defect

#1076 Fix where memeber or token with null permission
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadataDeserializer.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadataDeserializerTest.java
Labels: defect
