Repository line/centraldogma, pull requests merged in 2024-08, with the labels that each got.

#981 Add xDS group service.
  dependencies.toml
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/AuthUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresPermissionDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRoleDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataServiceInjector.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginInitContext.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  xds/src/main/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/group/v1/package-info.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/proto/centraldogma/xds/group/v1/xds_group.proto
  xds/src/test/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupServiceTest.java
Labels: new feature

#989 Include the project role of a request token or user in project API
  common/src/main/java/com/linecorp/centraldogma/common/ProjectRole.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/ProjectDto.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRole.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRoleDecorator.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Member.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/TokenRegistration.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/Project.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/RepositoryListener.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1ListProjectTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryListenerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  webapp/src/dogma/common/components/Deferred.tsx
  webapp/src/dogma/common/components/Loading.tsx
  webapp/src/dogma/common/components/UserRole.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/auth/ProjectRole.tsx
  webapp/src/dogma/features/filter/filterSlice.ts
  webapp/src/dogma/features/project/ProjectDto.ts
  webapp/src/dogma/features/project/Projects.tsx
  webapp/src/dogma/features/project/settings/credentials/CredentialForm.tsx
  webapp/src/dogma/features/project/settings/members/AppMemberDto.ts
  webapp/src/pages/_app.tsx
  webapp/src/pages/api/v1/projects/index.ts
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
Labels: improvement, breaking change, new feature

#988 Add xDS resource services.
  xds/src/main/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/cluster/v1/package-info.java
  xds/src/main/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/endpoint/v1/package-info.java
  xds/src/main/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/CentralDogmaXdsResources.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/JsonFormatUtil.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
  xds/src/main/java/com/linecorp/centraldogma/xds/listener/v1/XdsListenerService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/listener/v1/package-info.java
  xds/src/main/java/com/linecorp/centraldogma/xds/route/v1/XdsRouteService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/route/v1/package-info.java
  xds/src/main/proto/centraldogma/xds/cluster/v1/xds_cluster.proto
  xds/src/main/proto/centraldogma/xds/endpoint/v1/xds_endpoint.proto
  xds/src/main/proto/centraldogma/xds/listener/v1/xds_listener.proto
  xds/src/main/proto/centraldogma/xds/route/v1/xds_route.proto
  xds/src/test/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/DiscoveryServiceItTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/LdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsTestUtil.java
  xds/src/test/java/com/linecorp/centraldogma/xds/listener/v1/XdsListenerServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/route/v1/XdsRouteServiceTest.java
Labels: new feature

#1007 Ignore invalid configurations when migrating legacy mirrors and credentials
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationServiceTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirroringMigrationService.java
Labels: defect

#999 Add @ConsumseJson to contents API.
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
Labels: defect

#942 Add HTTP API for updating a token level
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenLevelRequest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
Labels: new feature

#1011 Log `TokenNotFoundException` at the debug level
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
Labels: cleanup

#1008 Register all envoy extension to MessageMarshaller
  dependencies.toml
  xds/build.gradle
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
Labels: cleanup

#984 Introduce `XdsCentralDogmaBuilder`
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria-xds/build.gradle
  client/java-armeria-xds/src/main/java/com/linecorp/centraldogma/client/armeria/xds/XdsCentralDogmaBuilder.java
  client/java-armeria-xds/src/main/java/com/linecorp/centraldogma/client/armeria/xds/package-info.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/AuthUpstreamTest.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/SimpleXdsUpstreamTest.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/TlsUpstreamTest.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/XdsResourceReader.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/XdsResourceReaderTest.java
  client/java-armeria-xds/src/test/resources/test-cluster-multiendpoint.yaml
  client/java-armeria-xds/src/test/resources/test-cluster.yaml
  client/java-armeria-xds/src/test/resources/test-listener.yaml
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/DnsAddressEndpointGroupConfigurator.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/package-info.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/internal/client/ReplicationLagTolerantCentralDogma.java
  dependencies.toml
  settings.gradle
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
Labels: new feature

#1015 Update dependencies
  client/java-armeria-xds/src/main/java/com/linecorp/centraldogma/client/armeria/xds/XdsCentralDogmaBuilder.java
  dependencies.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: dependencies

#980 Add xDS Kubernetes service
  dependencies.toml
  server/src/main/java/com/linecorp/centraldogma/server/internal/ExecutorServiceUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingService.java
  server/src/test/java/com/linecorp/centraldogma/server/MetricsTest.java
  xds/build.gradle
  xds/src/main/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/CentralDogmaXdsResources.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceWatchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingPlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/package-info.java
  xds/src/main/java/com/linecorp/centraldogma/xds/listener/v1/XdsListenerService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/route/v1/XdsRouteService.java
  xds/src/main/proto/centraldogma/xds/cluster/v1/xds_cluster.proto
  xds/src/main/proto/centraldogma/xds/endpoint/v1/xds_endpoint.proto
  xds/src/main/proto/centraldogma/xds/group/v1/xds_group.proto
  xds/src/main/proto/centraldogma/xds/k8s/v1/xds_kubernetes.proto
  xds/src/main/proto/centraldogma/xds/listener/v1/xds_listener.proto
  xds/src/main/proto/centraldogma/xds/route/v1/xds_route.proto
  xds/src/main/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
  xds/src/test/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CdsStreamingTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/DiscoveryServiceItTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/LdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsTestUtil.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/listener/v1/XdsListenerServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/route/v1/XdsRouteServiceTest.java
Labels: new feature

#1012 Reject invalid mirroring URI
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringAndCredentialServiceV1Test.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/MirrorConfig.java
  webapp/src/dogma/common/components/form/FieldErrorMessage.tsx
  webapp/src/dogma/features/auth/ProjectRole.tsx
  webapp/src/dogma/features/project/settings/ProjectSettingsView.tsx
  webapp/src/dogma/features/project/settings/mirrors/MirrorForm.tsx
Labels: defect

#1013 Remove a trailing slash in the webapp paths
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/auth/AuthProvider.java
  webapp/next.config.js
  webapp/public/android-chrome-192x192.png
  webapp/public/android-chrome-512x512.png
  webapp/public/apple-touch-icon.png
  webapp/public/favicon-16x16.png
  webapp/public/favicon-32x32.png
  webapp/public/favicon.ico
  webapp/public/site.webmanifest
  webapp/src/dogma/features/auth/Authorized.tsx
Labels: improvement, breaking change, dependencies

#1010 Check if the internal project and repos exist before creating them
  dist/src/conf/dogma.json
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/InternalProjectInitializer.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerExtension.java
Labels: improvement

#1016 Fix flaky ProjectServiceV1ListProjectTest
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1ListProjectTest.java
Labels: cleanup

#1017 Access JAR file only once to find Envoy extension classes
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
Labels: cleanup

#1018 Fix bugs in UI pagination
  webapp/src/dogma/common/components/UserRole.tsx
  webapp/src/dogma/common/components/table/DataTableClientPagination.tsx
  webapp/src/dogma/common/components/table/DynamicDataTable.tsx
  webapp/src/dogma/common/components/table/Filter.tsx
  webapp/src/dogma/common/components/table/PaginationBar.tsx
  webapp/src/dogma/features/auth/ProjectRole.tsx
  webapp/src/dogma/features/auth/authSlice.ts
  webapp/src/dogma/features/project/settings/ProjectSettingsView.tsx
Labels: defect

#1019 Fix directory link
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  webapp/src/dogma/features/file/FileList.tsx
  webapp/tests/dogma/feature/file/FileList.test.tsx
  xds/src/test/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupServiceTest.java
Labels: cleanup

#1020 Skip the directory entry when creating xDS resources at server startup
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceWatchingService.java
Labels: cleanup

#1021 Reload webpages when refreshed
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
Labels: defect

#1022 Avoid Using Future.join() During Control Plane Plugin Startup
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceWatchingService.java
Labels: improvement

#1023 `XdsCentralDogmaBuilder` accepts a `localClusterName` instead of `serviceCluster`
  client/java-armeria-xds/src/main/java/com/linecorp/centraldogma/client/armeria/xds/XdsCentralDogmaBuilder.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/ZoneAwareRoutingTest.java
  client/java-armeria-xds/src/test/resources/test-cluster-multizone.yaml
Labels: defect

#1024 Fix Deadlock Issue in Control Plane service
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlanePlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceWatchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingPlugin.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/CreatingInternalGroupPlugin.java
  xds/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
Labels: defect

#1025 Ensure Compliance with AIP Rules for Resource Creation and Update
  xds/src/main/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneExceptionHandlerFunction.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/listener/v1/XdsListenerService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/route/v1/XdsRouteService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsTestUtil.java
Labels: defect

#1027 Optimize Commit Frequency in Kubernetes Endpoint Fetching
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
Labels: improvement

#1026 Add a commit and compare view
  webapp/package-lock.json
  webapp/package.json
  webapp/src/dogma/common/components/ChakraLink.tsx
  webapp/src/dogma/common/components/CompareButton.tsx
  webapp/src/dogma/common/components/DiffModeButton.tsx
  webapp/src/dogma/common/components/DiffView.tsx
  webapp/src/dogma/common/components/FileIcon.tsx
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/common/components/table/DebouncedInput.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/file/FileDto.ts
  webapp/src/dogma/features/file/FileList.tsx
  webapp/src/dogma/features/history/HistoryList.tsx
  webapp/src/dogma/util/path-util.ts
  webapp/src/pages/404.tsx
  webapp/src/pages/_app.tsx
  webapp/src/pages/api/v1/projects/[projectName]/repos/[repoName]/commits/[revision].ts
  webapp/src/pages/api/v1/projects/[projectName]/repos/[repoName]/contents/[...fileName].ts
  webapp/src/pages/api/v1/projects/[projectName]/repos/[repoName]/list.ts
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/commit/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/commits/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/compare/[revision]/base/[baseRevision]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/tree/[revision]/[[...path]]/index.tsx
Labels: new feature

#1029 Fix regex for validating mirror remoteUrl
  webapp/src/dogma/features/project/settings/mirrors/MirrorForm.tsx
Labels: defect

#1028 Paginate the commit history page with query params
  webapp/src/dogma/common/components/Breadcrumbs.tsx
  webapp/src/dogma/common/components/CompareButton.tsx
  webapp/src/dogma/common/components/Deferred.tsx
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/common/components/table/DataTable.tsx
  webapp/src/dogma/common/components/table/DynamicDataTable.tsx
  webapp/src/dogma/common/components/table/PaginationBar.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/file/FileDto.ts
  webapp/src/dogma/features/history/HistoryList.tsx
  webapp/src/dogma/features/services/ErrorMessageParser.ts
  webapp/src/dogma/util/path-util.ts
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/commit/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/commits/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/compare/[revision]/base/[baseRevision]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/tree/[revision]/[[...path]]/index.tsx
Labels: improvement
