Repository line/centraldogma, pull requests merged in 2024-11, with the labels that each got.

#1041 Provide a way to trigger Git mirroring manually
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  common/src/main/java/com/linecorp/centraldogma/common/MirrorException.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/MirrorDto.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/ForceRefUpdateTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/GitMirrorIntegrationTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/LocalToRemoteGitMirrorTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/MirrorRunnerTest.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirror.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/mirror/git/GitMirrorException.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/mirror/git/SshMirrorException.java
  server-mirror-git/src/main/java/com/linecorp/centraldogma/server/mirror/git/package-info.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMetaRepositoryWithMirrorTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingServiceTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/SshGitMirrorTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/CsrfTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/auth/SessionTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/CentralDogmaMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirroringServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorRunner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/DefaultMetaRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/MirrorConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/Mirror.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorContext.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorResult.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorStatus.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/MergeFileTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingServicePluginTest.java
  webapp/package-lock.json
  webapp/package.json
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/common/components/NotificationWrapper.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/dogma/features/auth/Authorized.tsx
  webapp/src/dogma/features/mirror/MirrorResult.ts
  webapp/src/dogma/features/mirror/RunMirrorButton.tsx
  webapp/src/dogma/features/notification/notificationSlice.ts
  webapp/src/dogma/features/project/settings/mirrors/MirrorDto.ts
  webapp/src/dogma/features/project/settings/mirrors/MirrorForm.tsx
  webapp/src/dogma/features/project/settings/mirrors/MirrorList.tsx
  webapp/src/dogma/features/project/settings/mirrors/MirrorView.tsx
  webapp/src/dogma/features/services/ErrorMessageParser.ts
  webapp/src/dogma/store.ts
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
Labels: new feature

#1049 Fix a bug where `Created by me` filter fails to render
  webapp/src/dogma/features/project/Projects.tsx
Labels: defect

#1046 Support Aggregating Multiple Kubernetes Clusters into a Single xDS Cluster
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
  xds/src/main/proto/centraldogma/xds/k8s/v1/xds_kubernetes.proto
  xds/src/test/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/AggregatingMultipleKubernetesTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
Labels: new feature

#1047 Fix `:dist:copyLib` Task not to copy duplicate libraries
  dist/build.gradle
  server-auth/saml/build.gradle
  server-auth/shiro/build.gradle
  server-mirror-git/build.gradle
  xds/build.gradle
Labels: defect

#1050 Copy JCommander library to distribution directory
  dist/build.gradle
  server/build.gradle
Labels: defect

#1044 Provide a way to run a `Plugin` in a zone leader replica
  dependencies.toml
  it/server/build.gradle
  it/server/src/test/java/com/linecorp/centraldogma/it/ConfigValueConverterTest.java
  it/zone-leader-plugin/build.gradle
  it/zone-leader-plugin/src/test/java/com/linecorp/centraldogma/it/zoneleader/ZoneLeaderPluginTest.java
  it/zone-leader-plugin/src/test/java/com/linecorp/centraldogma/server/DynamicZoneResolverTest.java
  it/zone-leader-plugin/src/test/java/com/linecorp/centraldogma/server/MyZoneProvider.java
  it/zone-leader-plugin/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.ConfigValueConverter
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/DefaultConfigValueConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/PluginGroup.java
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/plugin/PluginTarget.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/Replica.java
  settings.gradle
  site/src/sphinx/setup-configuration.rst
  testing-internal/build.gradle
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaReplicationExtension.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerExtension.java
Labels: new feature

#1052 Remove Anonymous Role
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/AuthUpstreamTest.java
  common/src/main/java/com/linecorp/centraldogma/common/ProjectRole.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/MirrorRunnerTest.java
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringAndCredentialServiceV1Test.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/PerRolePermissions.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/User.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/PermissionTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataApiServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/PerRolePermissionsTest.java
  site/src/sphinx/auth.rst
  testing/common/src/main/java/com/linecorp/centraldogma/testing/internal/CentralDogmaRuleDelegate.java
  webapp/src/dogma/features/auth/ProjectRole.tsx
  webapp/src/dogma/features/project/settings/ProjectSettingsView.tsx
Labels: defect, improvement

#1055 Enable `respect_dns_ttl` by default for xDS cluster
  xds/src/main/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/cluster/v1/XdsClusterServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/XdsTestUtil.java
Labels: defect

#1053 Expose internal projects to users who have `MEMBER` permission
  client/java-armeria-legacy/src/main/java/com/linecorp/centraldogma/client/armeria/legacy/LegacyCentralDogma.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  common/src/main/java/com/linecorp/centraldogma/common/PermissionException.java
  common/src/main/java/com/linecorp/centraldogma/internal/Util.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/CreateProjectRequest.java
  it/xds-member-permission/build.gradle
  it/xds-member-permission/src/test/java/com/linecorp/centraldogma/server/test/XdsMemberPermissionTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/admin/service/RepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/CredentialServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/GitHttpService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/converter/HttpApiRequestConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorRunner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/ProjectApiManager.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/thrift/CentralDogmaServiceImpl.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  settings.gradle
  webapp/build.gradle
Labels: improvement

#1057 Provide a way to listen to the events of mirroring
  it/mirror-listener/src/test/java/com/linecorp/centraldogma/it/mirror/listener/CustomMirrorListenerTest.java
  it/mirror-listener/src/test/java/com/linecorp/centraldogma/it/mirror/listener/TestMirrorListener.java
  it/mirror-listener/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.mirror.MirrorListener
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/MirrorRunnerTest.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestMirrorRunnerListener.java
  it/mirror/src/test/resources/META-INF/services/com.linecorp.centraldogma.server.mirror.MirrorListener
  server-mirror-git/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MirroringTaskTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/AbstractMirror.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/CompositeMirrorListener.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirrorListener.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/InstrumentedMirroringJob.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorRunner.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/User.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/Mirror.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorListener.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorResult.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorTask.java
  settings.gradle
Labels: new feature

#1058 Set Default Values for Path and Branch Fields in Mirror UI
  webapp/src/dogma/features/project/settings/mirrors/MirrorForm.tsx
  webapp/src/pages/app/projects/[projectName]/settings/mirrors/new/index.tsx
Labels: miscellaneous

#1059 Move `Delete Project` button to `Danger zone` tab
  webapp/src/dogma/common/components/Navbar.tsx
  webapp/src/dogma/common/components/ProjectSearchBox.tsx
  webapp/src/dogma/features/project/DeleteProject.tsx
  webapp/src/dogma/features/project/settings/ProjectSettingsView.tsx
  webapp/src/pages/api/v1/projects/[projectName]/credentials/[id]/index.ts
  webapp/src/pages/api/v1/projects/[projectName]/credentials/index.ts
  webapp/src/pages/api/v1/projects/[projectName]/mirrors/[id]/index.ts
  webapp/src/pages/api/v1/projects/[projectName]/repos/[repoName]/list/[...fileName].ts
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/commit/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/commits/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/compare/[revision]/base/[baseRevision]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/files/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/permissions/index.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/tree/[revision]/[[...path]]/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/danger-zone/index.tsx
  webapp/src/pages/app/projects/[projectName]/settings/index.tsx
  webapp/src/pages/index.tsx
Labels: improvement
