Repository line/centraldogma, pull requests merged in 2025-08, with the labels that each got.

#1153 Add key version to metadata for encryption key rotation
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/encryption/EncryptionUtil.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/encryption/package-info.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/rocksdb/EncryptionGitStorage.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/rocksdb/GitObjectMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/encryption/DefaultEncryptionStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/encryption/EncryptionStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/encryption/NoopEncryptionStorageManager.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/encryption/SecretKeyWithVersion.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/EncryptedGitRepositoryRemoveTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/rocksdb/EncryptionGitStorageTest.java
  server/src/test/java/com/linecorp/centraldogma/server/storage/encryption/DefaultEncryptionStorageManagerTest.java
Labels: improvement

#1157 Abort watching on the initial failure
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/WatchRequestErrorTest.java
  client/java/src/main/java/com/linecorp/centraldogma/client/AbstractWatcher.java
Labels: defect

#1149 Do not enter readonly mode on lock timeout
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  common/src/main/java/com/linecorp/centraldogma/common/ApiRequestTimeoutException.java
  common/src/main/java/com/linecorp/centraldogma/common/LockAcquireTimeoutException.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/test/java/com/linecorp/centraldogma/server/ServerTimeoutTest.java
Labels: defect

#1160 Use OSSRH Staging API to publish artifacts
  gradle.properties
Labels: miscellaneous

#1161 Update dependencies
  client/java-armeria-xds/src/main/java/com/linecorp/centraldogma/client/armeria/xds/XdsCentralDogmaBuilder.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/TlsUpstreamTest.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/XdsResourceReader.java
  client/java-armeria-xds/src/test/java/com/linecorp/centraldogma/client/armeria/xds/ZoneAwareRoutingTest.java
  client/java-armeria-xds/src/test/resources/test-listener.yaml
  client/java-armeria-xds/src/test/resources/test-tls-cluster.yaml
  client/java-armeria/src/main/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilder.java
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
  dependencies.toml
  gradle/scripts/lib/java.gradle
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/internal/LdsStreamingMultipleClientsTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
Labels: dependencies

#1168 Hide unnecessary Dogma repository metadata from users
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Member.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/ProjectMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/TokenRegistration.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  webapp/src/dogma/features/project/settings/repositories/RepoMetaList.tsx
Labels: defect

#1167 Remove JGit5
  dependencies.toml
  dist/build.gradle
  server/build.gradle
Labels: miscellaneous

#1171 Enable LoggerService when Logback is chosen
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/test/java/com/linecorp/centraldogma/server/HealthCheckServiceTest.java
Labels: defect
