Repository line/centraldogma, pull requests merged in 2025-03, with the labels that each got.

#1099 Cache project metadata and tokens
  it/server/src/test/java/com/linecorp/centraldogma/it/CacheTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/WriteQuotaTestBase.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/ForwardingCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/auth/ApplicationTokenAuthorizer.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/sysadmin/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryCache.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/RepositoryWrapper.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableFindCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableFindLatestRevCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableHistoryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableMergeQueryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableMultiDiffCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableQueryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableSingleDiffCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CacheableCompareTreesCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CacheableObjectLoaderCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CachingTreeObjectReader.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Member.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/ProjectMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositorySupport.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Roles.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/TokenRegistration.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Tokens.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/InternalProjectInitializer.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/AbstractCacheableCall.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/CacheableCall.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/HasWeight.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/Repository.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1ListProjectTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/auth/RequiresRoleTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/command/CommandExecutorStatusManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/Replica.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/PurgeSchedulingServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataApiServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MissingRepositoryMetadataTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/TokenTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerExtension.java
  xds/src/main/java/com/linecorp/centraldogma/xds/group/v1/XdsGroupService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneService.java
Labels: improvement

#1093 Prohibit application tokens from accessing repositories with GUEST permission
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  it/xds-member-permission/src/test/java/com/linecorp/centraldogma/server/test/XdsMemberPermissionTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/sysadmin/TokenService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Token.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/TokenServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/TokenGuestPermissionTest.java
  webapp/src/dogma/features/token/NewToken.tsx
Labels: improvement

#1103 Update dependencies
  dependencies.toml
Labels: dependencies

#1105 Publish Snapshots as we do for Armeria
  .github/workflows/actions_build.yml
Labels: miscellaneous

#1107 Fix a bug where invalid file name is used for deleting a repository credential
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/CredentialServiceV1.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/CredentialServiceV1Test.java
  webapp/src/dogma/features/auth/RepositoryRole.tsx
  webapp/src/dogma/features/repo/settings/mirrors/MirrorList.tsx
  webapp/src/dogma/features/settings/SettingView.tsx
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/tree/[revision]/[[...path]]/index.tsx
Labels: defect

#1111 Update Armeria version to 1.32.2
  dependencies.toml
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/KubernetesTestFlagsProvider.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesServiceTest.java
  xds/src/test/resources/META-INF/services/com.linecorp.armeria.common.FlagsProvider
Labels: dependencies

#1104 Improve the server shutdown process
  it/server/src/test/java/com/linecorp/centraldogma/it/GracefulShutdownTest.java
  it/zone-leader-plugin/src/test/java/com/linecorp/centraldogma/it/zoneleader/ZoneLeaderPluginTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingService.java
Labels: improvement

#1112 Ensure Complete Kubernetes Endpoints Update
  dependencies.toml
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesService.java
Labels: defect

#1109 Pass the mirror creator and updater to `MirrorListener`
  it/mirror-listener/src/test/java/com/linecorp/centraldogma/it/mirror/listener/TestMirrorListener.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestMirrorRunnerListener.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MirroringServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/CompositeMirrorListener.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/DefaultMirrorListener.java
  server/src/main/java/com/linecorp/centraldogma/server/mirror/MirrorListener.java
Labels: new feature

#1098 Cache an entire repository to increase cache hit rate
  common-legacy/src/main/java/com/linecorp/centraldogma/internal/thrift/QueryConverter.java
  common/src/test/java/com/linecorp/centraldogma/internal/thrift/QueryConverterTest.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CacheableQueryCall.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepository.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/PathPatternFilter.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/repository/FindOption.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/cache/CachingRepositoryTest.java
Labels: improvement

#1114 Provide a way to register an LbEndpoint to the existing ClusterLoadAssignment
  xds/src/main/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointService.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/XdsResourceManager.java
  xds/src/main/proto/centraldogma/xds/endpoint/v1/xds_endpoint.proto
  xds/src/test/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsEndpointServiceTest.java
  xds/src/test/java/com/linecorp/centraldogma/xds/endpoint/v1/XdsRegisterEndpointTest.java
Labels: new feature

#1102 Prohibit pushing to internal project and repository
  webapp/src/dogma/common/components/editor/FileEditor.tsx
  webapp/src/dogma/features/api/apiSlice.ts
  webapp/src/pages/app/projects/[projectName]/repos/[repoName]/tree/[revision]/[[...path]]/index.tsx
Labels: defect

#1089 Expose JSON Patch operations as public API
  client/java-armeria/src/main/java/com/linecorp/centraldogma/internal/client/armeria/ArmeriaCentralDogma.java
  client/java/src/main/java/com/linecorp/centraldogma/client/CentralDogmaRepository.java
  common/src/main/java/com/linecorp/centraldogma/common/Change.java
  common/src/main/java/com/linecorp/centraldogma/common/TextPatchConflictException.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/AddOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/CopyOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/DualPathOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/JsonPatchConflictException.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/JsonPatchOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/MoveOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/PathValueOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/RemoveIfExistsOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/RemoveOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/ReplaceOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/SafeReplaceOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/TestAbsenceOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/TestOperation.java
  common/src/main/java/com/linecorp/centraldogma/common/jsonpatch/package-info.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/DiffProcessor.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/JsonNumEquals.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatch.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchException.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchOperation.java
  common/src/main/java/com/linecorp/centraldogma/internal/jsonpatch/package-info.java
  common/src/test/java/com/linecorp/centraldogma/common/jsonpatch/JsonPatchOperationIntegrationTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchOperationSerializationTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchOperationTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/JsonPatchTestSuite.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/RemoveIfExistsOperationTest.java
  common/src/test/java/com/linecorp/centraldogma/internal/jsonpatch/RemoveOperationTest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/CommitExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/repository/git/DefaultChangesApplier.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/TokenTest.java
Labels: new feature

#1118 Restore debouncing logic for Kubernetes endpoint updates
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
  xds/src/test/java/com/linecorp/centraldogma/xds/k8s/v1/AggregatingMultipleKubernetesTest.java
Labels: defect
