Repository line/centraldogma, pull requests merged in 2025-04, with the labels that each got.

#1121 Remove write quota implementation to reduce ZooKeeper load
  common/src/main/java/com/linecorp/centraldogma/common/TooManyRequestsException.java
  dist/src/conf/dogma.json
  it/server/src/test/java/com/linecorp/centraldogma/it/ReplicationWriteQuotaTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/StandaloneWriteQuotaTest.java
  it/server/src/test/java/com/linecorp/centraldogma/it/WriteQuotaTestBase.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogma.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaBuilder.java
  server/src/main/java/com/linecorp/centraldogma/server/CentralDogmaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/QuotaConfig.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/ForwardingCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/HttpApiExceptionHandler.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/MetadataApiService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/SettableSharedCount.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadataDeserializer.java
  server/src/test/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/command/CommandExecutorStatusManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ClusterBuilder.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/Replica.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperQuotaTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadataDeserializerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadataTest.java
  site/src/sphinx/setup-configuration.rst
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerExtension.java
  xds/src/main/java/com/linecorp/centraldogma/xds/internal/ControlPlaneExceptionHandlerFunction.java
Labels: defect

#1124 Update Armeria version to 1.32.5
  dependencies.toml
Labels: dependencies

#1123 Prepare migration to unify meta and dogma repositories
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/CommandType.java
  server/src/main/java/com/linecorp/centraldogma/server/command/ResetMetaRepositoryCommand.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MigratingMirrorToRepositoryService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/mirror/MirrorSchedulingService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/RemovingMetaRepositoryMetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/RemovingMetaRepositoryMetadataServicePlugin.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectManager.java
  server/src/main/java/com/linecorp/centraldogma/server/storage/project/Project.java
  server/src/main/resources/META-INF/services/com.linecorp.centraldogma.server.plugin.Plugin
  server/src/test/java/com/linecorp/centraldogma/server/internal/mirror/MigratingMirrorToRepositoryServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/RemovingMetaRepositoryMetadataServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectTest.java
  testing-internal/src/main/java/com/linecorp/centraldogma/testing/internal/ProjectManagerExtension.java
Labels: improvement

#1126 Allow overriding SAML ACS endpoint for proxy support
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthProperties.java
  server-auth/saml/src/main/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthProviderFactory.java
  server-auth/saml/src/test/java/com/linecorp/centraldogma/server/auth/saml/AuthenticationDeserializationTest.java
  server-auth/saml/src/test/java/com/linecorp/centraldogma/server/auth/saml/SamlAuthTest.java
  site/src/sphinx/auth.rst
Labels: improvement

#1122 Add support for setting individual repository to read-only mode
  common/src/main/java/com/linecorp/centraldogma/common/RepositoryStatus.java
  common/src/main/java/com/linecorp/centraldogma/internal/api/v1/RepositoryDto.java
  it/xds-member-permission/src/test/java/com/linecorp/centraldogma/server/test/XdsMemberPermissionTest.java
  server/src/main/java/com/linecorp/centraldogma/server/command/AbstractCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/command/Command.java
  server/src/main/java/com/linecorp/centraldogma/server/command/StandaloneCommandExecutor.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/DtoConverter.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/ProjectServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/UpdateRepositoryStatusRequest.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/api/sysadmin/ServerStatusService.java
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/MetadataService.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositoryMetadata.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/RepositorySupport.java
  server/src/main/java/com/linecorp/centraldogma/server/metadata/Roles.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/admin/model/SerializationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/RepositoryServiceV1Test.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/api/ServerStatusServiceTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/command/CommandExecutorStatusManagerTest.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/replication/ZooKeeperCommandExecutorTest.java
  server/src/test/java/com/linecorp/centraldogma/server/management/ServerStatusManagerIntegrationTest.java
  server/src/test/java/com/linecorp/centraldogma/server/metadata/MetadataServiceTest.java
  xds/src/main/java/com/linecorp/centraldogma/xds/k8s/v1/XdsKubernetesEndpointFetchingService.java
Labels: new feature

#1129 Fix missing migration marker file in dogma repository
  server/src/main/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProject.java
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/project/DefaultProjectTest.java
Labels: defect

#1130 Fix flaky test `ArmeriaCentralDogmaBuilderTest`
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/ArmeriaCentralDogmaBuilderTest.java
  client/java-armeria/src/test/java/com/linecorp/centraldogma/client/armeria/TestDnsServer.java
  client/java-armeria/src/test/resources/centraldogma-profiles-test.json
Labels: cleanup

#1133 Fix flaky test in ZoneAwareMirrorTest
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/TestZoneAwareMirrorListener.java
  it/mirror/src/test/java/com/linecorp/centraldogma/it/mirror/git/ZoneAwareMirrorTest.java
Labels: cleanup

#1134 Fix flaky test in GitRepositoryListenerTest
  server/src/test/java/com/linecorp/centraldogma/server/internal/storage/repository/git/GitRepositoryListenerTest.java
Labels: cleanup
